safe-global/safe-transaction-service

.travis.yml, config/settings/base.py, requirements.txt, safe_transaction_service/history/admin.py, safe_transaction_service/history/indexers/erc20_events_indexer.py, safe_transaction_service/history/indexers/ethereum_indexer.py, safe_transaction_service/history/indexers/internal_tx_indexer.py, safe_transaction_service/history/indexers/tx_processor.py, safe_transaction_service/history/management/commands/process_txs_again.py, safe_transaction_service/history/management/commands/setup_service_rinkeby.py, safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/__init__.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/factories.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
- Create new endpoint
- Fix internal trace indexing
- Add tests
- Improve admin
- Use algorithm to optimize processing of traces/erc20
- Improve logging
=> Implement token balance endpoint

.travis.yml, config/settings/base.py, requirements.txt, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
- Add a new endpoint `/v1/safes/<safe>/balances/usd/`
- Use Uniswap oracle
- Add tests
- Closes #38
=> Estimate balance in fiat

safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py, safe_transaction_service/templates/drf-yasg/swagger-ui.html
=> Get Safes by owner

config/settings/base.py, docker/web/run_web.sh, safe_transaction_service/history/management/commands/send_slack_notification.py
- Add send_slack_notification commandline.
- Add send message to slack with the name of the app and the version.
=> Notify new transaction history releases in slack

safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/services/transaction_service.py, safe_transaction_service/history/tests/test_balance_service.py, safe_transaction_service/history/tests/test_collectibles_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/utils.py, safe_transaction_service/history/views.py, safe_transaction_service/tokens/admin.py
- Migrate db models
- Adjust admin interface
- Add query parameters for balances/collectibles endpoints
- Add tests
- Refactor balances/collectibles views
=> Add trusted and spam flags to tokens

config/settings/base.py, docker/nginx/nginx.conf, safe_transaction_service/history/utils.py, safe_transaction_service/history/views.py
=> Add middleware to profile endpoint times

requirements-test.txt, requirements.txt, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/transaction_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
=> Add endpoint to estimate txs

safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/test_balance_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_tasks.py
=> Add timestamp for fiat calculation

safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/tests/test_collectibles_service.py
=> Optimize collectibles get uris/metadata

safe_transaction_service/history/services/balance_service.py, safe_transaction_service/tokens/serializers.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_views.py, safe_transaction_service/tokens/urls.py, safe_transaction_service/tokens/views.py
=> Create endpoint to get fiat conversion for a token

.env, config/celery_app.py, config/settings/base.py, requirements.txt, safe_transaction_service/history/indexers/safe_events_indexer.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_tasks.py
=> Add prices for Curve/PoolTogether

.env.dev, README.md
=> Add development instructions to README

safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/clients/test_coingecko_client.py
=> Support BSC and MATIC prices with coingecko

.github/workflows/python.yml, requirements.txt, safe_transaction_service/__init__.py
Parsing of balances was not ok on `gnosis-py` previous version
Updating `gnosis-py`
=> Fix balances parsing issue

safe_transaction_service/__init__.py, safe_transaction_service/history/models.py, safe_transaction_service/history/services/balance_service.py
- Events query `DISTINCT` was not working
- Remove `id` from the query
=> Optimize events query

config/settings/base.py, safe_transaction_service/contracts/management/commands/index_contracts_with_metadata.py, safe_transaction_service/contracts/tasks.py, safe_transaction_service/contracts/tests/test_tasks.py, safe_transaction_service/history/management/commands/setup_service.py
Closes #344 making contract ABI checking a low priority task
=> Add task priority

safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/views.py
=> Revoke all delegates

safe_transaction_service/history/views.py, safe_transaction_service/notifications/tasks.py
=> Fix swagger

docker/web/celery/worker/run.sh
I'm suspicious of celery autoscaler having issues and it's not really needed for our use case
=> Disable celery autoscale

safe_transaction_service/history/management/commands/setup_service.py
- Related to #398 and https://github.com/gnosis/safe-deployments/pull/19
=> Support AVALANCHE Safe contracts

requirements.txt
Closes https://github.com/gnosis/safe-transaction-service/issues/302#issuecomment-880714463 (second point)
more info in https://github.com/gnosis/gnosis-py/pull/96
=> Fix wrong fiat price for curve gauge tokens

safe_transaction_service/__init__.py, safe_transaction_service/history/migrations/0045_erc20transfer_erc721transfer.py
Regular migration was slow in some cases
=> Use RAW SQL for EthereumEvent migration

safe_transaction_service/contracts/tasks.py, safe_transaction_service/history/models.py
Module ABIs were not automatically indexed
Index Module ABIs with Multisig Transactions ABIs
=> Auto index module ABIs

safe_transaction_service/history/models.py, safe_transaction_service/history/tasks.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_safe_events_indexer.py, safe_transaction_service/history/tests/test_tasks.py
=> Auto reindex when an indexing issue is found for a Safe

safe_transaction_service/__init__.py
- Include auto reindexing when missing transactions are detected
=> Set version 3.4.6

safe_transaction_service/history/admin.py, safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/history/models.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tasks.py, safe_transaction_service/history/tests/test_commands.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_tasks.py
=> Reindex last hour txs

README.md, safe_transaction_service/history/indexers/safe_events_indexer.py
- Add Safe addresses to the README
- Closes #489
=> Make SafeEventsIndexer DB error more clear

safe_transaction_service/history/management/commands/setup_service.py
- Related to https://github.com/gnosis/safe-deployments/pull/34
=> Support optimistic contracts

safe_transaction_service/__init__.py, safe_transaction_service/history/tasks.py, safe_transaction_service/utils/tasks.py
Iterators seem to have issues when modifying the underlying data
=> Revert use iterators

scripts/deploy_docker.sh
- Currently caching of docker builds is not working on the CI
=> Add cache information for docker images

requirements.txt, safe_transaction_service/history/management/commands/setup_service.py
- Depends on https://github.com/gnosis/gnosis-py/pull/142
- Depends on https://github.com/gnosis/safe-deployments/pull/39
=> Add gather contracts

safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/tests/clients/test_ens_client.py, safe_transaction_service/history/tests/test_collectibles_service.py, safe_transaction_service/history/tests/test_views.py
- Increase IPFS timeout 5 -> 10
=> Fix ENS and IPFS tests

safe_transaction_service/history/migrations/0050_ethereum_address_field_v2_20211201_1507.py
- Using COMMIT breaks Django migration system
=> Fix migration

safe_transaction_service/history/indexers/ethereum_indexer.py, safe_transaction_service/history/models.py, safe_transaction_service/history/signals.py, safe_transaction_service/history/tasks.py
- Add more debug logging information
=> Increase debug logging

safe_transaction_service/history/signals.py, safe_transaction_service/history/tests/test_signals.py
- Webhooks were not triggered when reindexing, as they were considered old and not relevant
- Notifications were only considered relevant when they are newer than 10 minutes, so with Optimism batches and potentially other networks there are issues
- Webhooks will be triggered always
- Increase notification relevant threshold from 10 -> 30 minutes
=> Send webhooks always

config/settings/base.py, docker/web/celery/worker/run.sh
=> Refactor celery configuration

config/settings/base.py, docker/web/celery/worker/run.sh
Remove CELERYD from Django configuration, worker is complaining and not working, revert to the old configuration via command line
=> Fix celery worker not processing tasks

config/settings/base.py, safe_transaction_service/contracts/tasks.py, safe_transaction_service/history/models.py, safe_transaction_service/history/tasks.py, safe_transaction_service/notifications/tasks.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/utils/utils.py
It looks like sometimes postgres connections can stay open
Close postgres connections in every task
=> Make sure tasks close postgres connections

config/settings/base.py, safe_transaction_service/__init__.py, safe_transaction_service/history/views.py
- Backmerge of `3.4.22` and `3.4.23`
=> 3.4.23 Hotfix Backmerge

.github/workflows/cla.yml
=> Add CLA to github actions

requirements.txt, safe_transaction_service/__init__.py
This version will include big database migrations for `EthereumAddressField` and `Sha3Field`
=> Bump version to v4.0.0

config/settings/base.py, safe_transaction_service/history/models.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/services/reorg_service.py, safe_transaction_service/history/tests/test_models.py
- Increase number of reorg blocks for L2 to 100
- Closes #628
=> Fix reorgs issues for blocks with same block number

safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/history/models.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tasks.py, safe_transaction_service/history/tests/test_index_service.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_tasks.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/views.py
- Closes #505
No notifications when a service was out of sync
Check every 10 minutes if service is out of sync and log if it is
=> Add task to check if service is out of sync

config/settings/base.py
=> Enable CSRF

safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
=> Support AURORA network

safe_transaction_service/contracts/models.py, safe_transaction_service/contracts/tests/test_models.py
- Old ABI will be updated with the saved attributes
=> Fix inserting duplicated ABI

safe_transaction_service/history/management/commands/setup_service.py
Would you consider upstreaming this change. It would save the Metis team from having to maintain a fork of this repo.
Closes #
=> Support metis contracts

safe_transaction_service/history/management/commands/setup_service.py
- They need to be merged on https://github.com/gnosis/safe-deployments/pull/39
=> Remove Gather contracts

safe_transaction_service/contracts/signals.py, safe_transaction_service/contracts/views.py, safe_transaction_service/history/signals.py
=> Invalidate contracts cache when contract/ABI is updated

requirements.txt, safe_transaction_service/__init__.py
- More info: https://github.com/gnosis/gnosis-py/pull/195
=> Fix decoding ERC20/721 Transfer events

requirements-dev.txt, safe_transaction_service/__init__.py, safe_transaction_service/contracts/tx_decoder.py, safe_transaction_service/history/clients/ens_client.py, safe_transaction_service/history/indexers/ethereum_indexer.py, safe_transaction_service/history/indexers/events_indexer.py, safe_transaction_service/history/indexers/safe_events_indexer.py, safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/services/safe_service.py, safe_transaction_service/history/signals.py, safe_transaction_service/history/tests/test_transaction_service.py, safe_transaction_service/history/tests/test_tx_processor.py, safe_transaction_service/notifications/serializers.py, safe_transaction_service/notifications/tests/factories.py, safe_transaction_service/tokens/clients/coinmarketcap_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/utils/utils.py
After running pylint using:
```
pip install pylint pylint-django
DJANGO_SETTINGS_MODULE=config.settings.test DJANGO_DOT_ENV_FILE=.env.test pylint --load-plugins pylint_django safe_transaction_service | grep ': R1'
```
A lot of issues appeared. Some of them were ignored but some others were fixed. There are even some optimizations (e.g. using generators instead of list comprehensions)
=> Fix Pylint issues

safe_transaction_service/history/models.py
- Currently it has to be fixed manually
=> Fix missing blocks due to a reorg when detected

safe_transaction_service/__init__.py, safe_transaction_service/tokens/models.py, safe_transaction_service/tokens/tests/test_models.py
- Fix creating token with null bytes on name/symbol
- Set version 4.2.6
=> Fix creating token with null bytes on name/symbol

config/settings/base.py, safe_transaction_service/history/views.py
=> Make owners API cache configurable

.github/workflows/python.yml, scripts/autodeploy.sh
- Removed Dockerhub autodeploy weebhooks
- Added new step for the autodeploy request after the image is built
- Added auth to autodeploy service, now is more secure the deployment of new versions.
=> Refactor Autodeploy

requirements.txt
- Closes #713
- More info on https://gnosis-py.readthedocs.io/en/latest/quickstart.html#gnosis-eth
=> Make EthereumClient timeouts configurable

safe_transaction_service/tokens/views.py
- `price_service` already holds a reference to the singleton `PriceServiceProvider` so we can use it
=> Use price_service reference in TokenPriceView

safe_transaction_service/history/models.py
Get Safe by owner query is quite slow. A new query that takes half the time is proposed. Current query
```sql
SELECT DISTINCT(address)
FROM (
SELECT address, owners,
rank() OVER (PARTITION BY address ORDER BY nonce DESC, internal_tx_id DESC) AS pos
FROM history_safestatus
WHERE address IN (
SELECT address FROM history_safestatus
WHERE owners @> ARRAY[%s]::bytea[]
)
) AS ss
WHERE pos = 1 AND owners @> ARRAY[%s]::bytea[];
```
```
Unique  (cost=13777.67..20363.74 rows=1 width=21) (actual time=47.230..55.125 rows=545 loops=1)
->  Subquery Scan on ss  (cost=13777.67..20363.73 rows=1 width=21) (actual time=47.229..54.961 rows=545 loops=1)
Filter: ((ss.owners @> '{"ETHEREUM_ADDRESS"}'::bytea[]) AND (ss.pos = 1))
Rows Removed by Filter: 255
->  WindowAgg  (cost=13777.67..19711.50 rows=43482 …
```
=> Optimize owners query

safe_transaction_service/notifications/tasks.py
=> Return only firebase cloud messaging token when querying DB

requirements.txt, safe_transaction_service/__init__.py, safe_transaction_service/history/indexers/tx_processor.py
- Cache ethereum RPC chainId always
- Set version 4.2.10
=> Cache ethereum RPC chainId always

safe_transaction_service/__init__.py
- Fix Django SQLi: https://docs.djangoproject.com/en/4.0/releases/3.2.13/
=> Set version 4.2.11

requirements-test.txt
Reverts safe-global/safe-transaction-service#809
=> Revert "Bump mypy from 0.942 to 0.950"

config/settings/base.py, config/settings/production.py, docker/web/celery/scheduler/run.sh, docker/web/celery/worker/run.sh
- Allow configuration of `CELERY_RESULT_BACKEND`
- Install `flower` for monitoring on the scheduler
=> Configure CELERY_RESULT_BACKEND

docker-compose.yml, docker/web/celery/scheduler/run.sh, docker/web/celery/worker/run.sh, requirements.txt
- Run flower on scheduler machine (default port 5555)
=> Use flower for celery monitoring

safe_transaction_service/tokens/clients/coinmarketcap_client.py
- They changed platform object and made our client broke
=> Fix coinmarketcap client

docker/web/celery/scheduler/run.sh
=> Don't exec `celery`

README.md, docker-compose.yml, docker/web/celery/flower/run.sh, docker/web/celery/scheduler/run.sh
- Scheduler is too important to risk having issues with it
=> Run flower in a different container

config/settings/base.py, safe_transaction_service/contracts/tasks.py, safe_transaction_service/history/signals.py
- https://www.rabbitmq.com/priority.html#overview
- https://docs.celeryq.dev/en/latest/userguide/routing.html#rabbitmq-message-priorities
=> Use RabbitMQ recommended configuration

safe_transaction_service/history/indexers/ethereum_indexer.py
- Get minimum block number using the first address provided
=> Save 1 db query in the indexer

safe_transaction_service/__init__.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/views.py
- Return SafeStatus always from blockchain
- Revert `SafeLastStatus` changes to the Safe info view
- Set version 4.3.3
=> Return SafeStatus always from blockchain

safe_transaction_service/__init__.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/notifications/serializers.py, safe_transaction_service/notifications/tests/test_views.py, safe_transaction_service/notifications/utils.py, safe_transaction_service/notifications/views.py, safe_transaction_service/utils/serializers.py
- It failed with some nodes and doesn't make a big change
- Refactored some code
=> Disable pending blocks for owner retrieval

safe_transaction_service/history/tests/test_tx_processor.py
- Wrote a new test while fixing #895
=> Improve tx-processor testing

config/settings/local.py, requirements-dev.txt
- Add shell_plus to dev environment
=> Add shell_plus to dev env

docker/web/Dockerfile, requirements.txt, safe_transaction_service/contracts/models.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/views.py, safe_transaction_service/notifications/utils.py, safe_transaction_service/tokens/clients/coinmarketcap_client.py, safe_transaction_service/tokens/management/commands/add_token.py, safe_transaction_service/tokens/tests/clients/test_coinmarketcap_client.py, safe_transaction_service/tokens/tests/clients/test_kleros_client.py, safe_transaction_service/tokens/views.py
- Related to https://github.com/safe-global/safe-eth-py/pull/269
=> Optimize EIP55 address calculation

gunicorn.conf.py, safe_transaction_service/__init__.py
- Mitigate gunicorn memory leaks
- Set version 4.3.8
=> Mitigate gunicorn memory leaks

requirements.txt, safe_transaction_service/history/management/commands/setup_service.py
Missing safe contract addresses for Venidium Testnet network 
Added safe contract addresses for Venidium Testnet
﻿@gnosis/safe-services
=> add Venidium testnet safe contracts

safe_transaction_service/history/models.py
- Use a proper query instead of returning all elements and do the processing on Python
- Related to https://github.com/safe-global/safe-pm/issues/89
=> Optimize collectibles DB query

safe_transaction_service/history/management/commands/setup_service.py
- As database is checked first performance should not be affected
=> Reduce tx indexing pooling interval from 13 -> 5 seconds

requirements.txt, safe_transaction_service/__init__.py
- Add limit for batch requests
- Set version 4.5.0
=> bump version

safe_transaction_service/history/services/collectibles_service.py
The new place where pagination is applied is going to be better to reduce the queries to database or blockchain node. 
=> Improve performance collectibles pagination

gunicorn.conf.py
- Previously it was 100_000 queries
=> Auto restart gunicorn workers on 20_000 queries

requirements.txt
=> Remove authtools

safe_transaction_service/tokens/views.py
- It was showing limit and offset on Swagger
=> Fix swagger for TokenPrice endpoint

safe_transaction_service/history/management/commands/setup_service.py
Cronos testnet and mainnet were missing the setup service.
=> Add cronos chain to setup_service

requirements.txt
=> Bump django to v4.0.7

safe_transaction_service/tokens/clients/kucoin_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
The Cronos network had wrong prices.
Implemented a `CRO-USDT` price pair on Kucoin. 
And by the way, refactored the code of KuCoin to match that of the BinanceClient.
=> Implement prices for the Cronos chain

requirements.txt, safe_transaction_service/history/tests/test_safe_events_indexer.py, safe_transaction_service/tokens/clients/kucoin_client.py
=> Update safe-eth-py to v4.4.0

safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_price_service.py, safe_transaction_service/tokens/tests/test_tasks.py
Closes #1019 
- Store and return the last valid price if cannot obtain prices from external services. 
- Refactor calculate_token_eth_price_task
=> Recover and store again last price if cannot get price

safe_transaction_service/__init__.py, safe_transaction_service/history/indexers/erc20_events_indexer.py, safe_transaction_service/history/indexers/events_indexer.py
- Sequencial calls should be fast enough and will prevent hanging the nodes
=> Disable parallel RPC fetching of events

safe_transaction_service/tokens/clients/binance_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
=> Use binance as a price source for AURORA

safe_transaction_service/history/management/commands/send_slack_notification.py, safe_transaction_service/history/tasks.py
- Webhooks and slack could hang indefinitely
=> Add timeouts for missing POST requests

safe_transaction_service/history/management/commands/check_index_problems.py, safe_transaction_service/history/models.py
- Optimize nonce retrieval
- Print block number where the first issue was found
- Nonce query batch size was increased from `100` to `1000`, performance seems better this way
=> Optimize check index problems

safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
- Refactor ERC20Indexing endpoint into service
=> Add /about/indexing endpoint

safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
- Refactor oracle setup
- Closes #645
=> Add cowswap and uniswap V3 oracles

safe_transaction_service/history/services/transaction_service.py
- Don't use a join for multisig hashes and module hashes. Check is faster when using the actual tables with their indexes
- Use `UNION ALL` instead of `UNION`. There are already checks for duplicated elements
- Force a pre-sort of tables by timestamp DESC. That way PostgreSQL optimizer will use a heapsort instead of quicksort
Before:
```
Disk: 643080kB (for ERC20)
Planning Time: 1.834 ms
Execution Time: 20388.061 ms
```
After:
```
Disk usage: 154936kB (for ERC20) 
Planning Time: 1.904 ms
Execution Time: 6629.214 ms
```
=> Optimize all transactions query

safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/services/price_service.py
Adds token prices on fuse network to the safe-transaction-service
by adding coingecko support for fuse network
=> Add fuse network prices

safe_transaction_service/history/management/commands/setup_service.py
Add cloudwalk testnet
The chain is already added in https://github.com/safe-global/safe-eth-py
=> Add cloudwalk_testnet

safe_transaction_service/history/management/commands/setup_service.py
kcc mainnet and testnet were missing the setup service.
=> Add kcc mainnet and testnet to setup_service

requirements.txt
=> Bump safe-eth-py to v4.5.2

safe_transaction_service/history/management/commands/setup_service.py
[safe-deployments PR](https://github.com/safe-global/safe-deployments/pull/123) and check network name
exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/pull/375)
Closes #
=> add rabbit chain

safe_transaction_service/__init__.py, safe_transaction_service/history/services/collectibles_service.py
- Fix `retry_get_metadata_task` arguments
=> Set v4.11.2

safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/services/price_service.py
=> add metis network prices

safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/clients/kucoin_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
by adding kucoin and coingecko support for kcc network
=> Add kcc network prices

scripts/deploy_docker.sh
- `staging` images were tagged as `latest`
- Only releases will be tagged as `latest`
=> Use docker latest tag for releases

scripts/deploy_docker.sh
- Changes `gnosispm` to `safeglobal` when building and pushing Docker images
=> Update org in docker images

requirements.txt
=> Bump safe-eth-py version

requirements.txt, safe_transaction_service/tokens/services/price_service.py
- Closes #772
- Depends on https://github.com/safe-global/safe-eth-py/pull/387 and https://github.com/safe-global/safe-eth-py/pull/388
=> Add superfluid oracle oracle

safe_transaction_service/tokens/clients/kraken_client.py, safe_transaction_service/tokens/services/price_service.py, safe_transaction_service/tokens/tests/test_price_service.py
What was wrong?
Milkomeda-wrapped Algorand tokens had incorrect prices on a custom network.
How was it fixed?
Added Algorand pricing
Thanks folks 😸
=> Add ALGO prices for milkomeda Algorand

config/urls.py
=> Rename `safe-messages/` endpoints to `messages/`

safe_transaction_service/contracts/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/tasks.py, safe_transaction_service/history/tests/factories.py, safe_transaction_service/history/utils.py, safe_transaction_service/history/views_v2.py, safe_transaction_service/notifications/clients/firebase_client.py, safe_transaction_service/notifications/serializers.py, safe_transaction_service/safe_messages/serializers.py, safe_transaction_service/tokens/tasks.py
- Used pylint to find issues (`pylint --disable=C0115,C0116,C0301,C0114,E1120,E1101,W0223,R0801,C0103 --ignore-patterns='test*' safe_transaction_service`)
- Pylint reports a lot of issues that are not relevant, though there were some things we could improve
=> Fix linting issues

safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/tokens/services/price_service.py
https://github.com/safe-global/safe-deployments/pull/161
https://github.com/safe-global/safe-eth-py/pull/379
=> add metis goerli

requirements.txt, safe_transaction_service/history/management/commands/setup_service.py
What was wrong?
Configurations for Arbitrum Goerli was missing
Depends on https://github.com/safe-global/safe-eth-py/pull/406
=> Add ARBITRUM_GOERLI

safe_transaction_service/history/views.py
=> Return always `uniqueNonce` even if count is 0

.github/workflows/python.yml
- For every push on a PR two jobs were launched on the CI
=> Don't run CI on PRs twice

safe_transaction_service/__init__.py, safe_transaction_service/history/models.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tests/test_index_service.py, safe_transaction_service/history/tests/test_models.py
=> Prevent stuck Safes after a reorg

safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_views.py
=> Return valid JSON for origin field

safe_transaction_service/history/models.py, safe_transaction_service/tokens/clients/kucoin_client.py, safe_transaction_service/tokens/services/price_service.py
- Set default block/tx parameters for CELO to work (`gasLimit=0` for blocks and `gasPrice=0` for transactions)
- Support CELO prices
- Closes #1271
=> Support CELO network

config/settings/base.py
App must be enabled so tasks are registered
- Closes #1263
=> Enable analytics app

safe_transaction_service/analytics/tasks.py
`last_year` should be 1 year not 3
=> Fix last_year in get_transactions_per_safe_app_task

safe_transaction_service/__init__.py
- https://github.com/safe-global/safe-transaction-service/pull/1279
=> Set version 4.14.1

safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_tasks.py
- Follow the convention we are using for task names
=> Rename update_token_info_from_token_list to update_token_info_from_token_list_task

safe_transaction_service/tokens/services/price_service.py
- Only log success, so logs get cleaner and more useful
- Closes https://github.com/safe-global/safe-transaction-service/issues/1095
=> Don't log price retrieval failures

requirements.txt, safe_transaction_service/safe_messages/tests/test_models.py
=> Bump safe-eth-py

safe_transaction_service/contracts/admin.py
=> Add `Find ABI` menu for contracts admin page

requirements.txt, safe_transaction_service/__init__.py, safe_transaction_service/history/management/commands/setup_service.py
- Setup Base Goerli Testnet contracts
- Set version 4.15.2
=> Add base testnet contracts

safe_transaction_service/history/tests/clients/test_ens_client.py
Rinkeby is deprecated, so we replace it by Goerli
=> Replace Rinkeby for Goerli on ENS tests

safe_transaction_service/history/management/commands/setup_service.py
- https://github.com/safe-global/safe-deployments/pull/191
https://github.com/bobanetwork/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py#L543
https://github.com/bobanetwork/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py#L558
- Missing Boba Safe deployments
- Remove Boba Rinkeby as it doesn't exist anymore
Adding them
=> Adding Boba BNB and AVAX

README.md
I'm trying to address some frequent questions we get about the service
=> Add a small FAQ to the README

requirements.txt, safe_transaction_service/__init__.py
- Fix dependency loop
- Set version 4.18.2
=> Fix dependency loop

safe_transaction_service/history/indexers/ethereum_indexer.py, safe_transaction_service/history/tests/test_safe_events_indexer.py
=> Fix auto block adjustment for indexing

safe_transaction_service/history/indexers/events_indexer.py, safe_transaction_service/history/indexers/safe_events_indexer.py
- Support events with same topic but different indexed parameters on EventIndexer
- Closes #1388
=> Allow multiple ABIs per topic for decoding

safe_transaction_service/history/models.py, safe_transaction_service/history/tests/factories.py, safe_transaction_service/history/tests/test_models.py
- Add `__str__` method for IndexingStatus
=> Add test for IndexingStatus

safe_transaction_service/history/management/commands/check_index_problems.py, safe_transaction_service/history/services/index_service.py
`check_index_problems` tries to find issues with Safes and detect the first problematic transaction, so it was easy to refactor it to try to reindex missing transactions and not having to do that manually after
=> Make `check_index_problems` auto reindex Safes

safe_transaction_service/history/indexers/erc20_events_indexer.py
- More context: https://github.com/celo-org/celo-blockchain/discussions/2079
- The added check should only be relevant for CELO and not interfere with other chains
=> Fix ERC20 indexing for CELO

config/settings/base.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/test_balance_service.py
- Add configurable batch requests for token balances
=> Fix ERC20 get_balances HTTP 413

config/settings/base.py, safe_transaction_service/__init__.py, safe_transaction_service/history/indexers/erc20_events_indexer.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/tests/test_balance_service.py, safe_transaction_service/tokens/clients/coingecko_client.py
- Add Celo and Polygon ZKEvm coingecko support #1430 
- Fix ERC20 indexing for CELO #1445 
- Fix ERC20 get_balances HTTP 413 #1446
=> v4.18.15 Hotfix

safe_transaction_service/__init__.py, safe_transaction_service/history/indexers/erc20_events_indexer.py
- Another check was missing
- Set version v4.18.6
=> Fix Celo ERC20 indexing

safe_transaction_service/history/helpers.py, safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
Closes #1230 
**For Token Transfer**
- `transfer_id = e+tx_hash+log_index` ex: `e5a6754140f0432d3b5e6d8341597ec3c5338239f8d311de9061fbc959f443d590,1`
**For Ethereum Transfer**
- `transfer_id = i+tx_hash+trace_address` ex: `i5a6754140f0432d3b5e6d8341597ec3c5338239f8d311de9061fbc959f443d590`
**For Module Transaction**
- `module_transaction_id = i+tx_hash+trace_address` ex: `i5a6754140f0432d3b5e6d8341597ec3c5338239f8d311de9061fbc959f443d590`
```
{
"count": 2,
"next": null,
"previous": null,
"results": [
{
"type": "ETHER_TRANSFER",
"executionDate": "2023-03-10T12:51:43.725712Z",
"blockNumber": 3,
"transactionHash": "0x5fcbf76f54cbf6ba517602624a5011a8fcce0a29ddafded053e7226c893a2380",
"to": "0xBbc411E0bCEEb43c21D66AfC99270E806DE506F3",
"value": "5",
"tokenId": null,
"tokenAddress": null, …
```
=> Add unique identifiers for moduleTransaction and transfers

config/settings/base.py, safe_transaction_service/__init__.py
Quotation was incorrect configuring the send_webhooks_task queue
=> Fix send_webhooks_task route configuration

safe_transaction_service/history/tests/test_collectibles_service.py
Reverts safe-global/safe-transaction-service#1477
=> Revert "Fix collectibles test"

safe_transaction_service/history/indexers/internal_tx_indexer.py
=> Add ValueError exception for trace_filter

safe_transaction_service/history/indexers/ethereum_indexer.py
=> Fix logging optional as int

.github/workflows/python.yml, config/settings/base.py, config/settings/test.py, docker-compose.yml, requirements.txt, run_tests.sh, safe_transaction_service/events/apps.py, safe_transaction_service/events/services/queue_service.py, safe_transaction_service/events/tasks.py, safe_transaction_service/events/tests/test_queue_service.py, safe_transaction_service/events/tests/test_tasks.py, safe_transaction_service/history/signals.py, safe_transaction_service/history/tests/test_signals.py
Closes #1007 
- add class to manage asynchronous connection (`gevent`) with `rabbitmq`.
- add class to manage synchronous connection for testing purposes. 
- add mock class to don't connect when there is not `rabbitmq` host configured.
- add singleton provider class to keep only one connection opened.
=> Send events to queue

config/settings/base.py, safe_transaction_service/__init__.py
- More info: https://www.postgresql.org/docs/current/runtime-config-client.html
=> Add postgres statement_timeout to prevent database overloaded

config/settings/base.py, safe_transaction_service/__init__.py, safe_transaction_service/contracts/tasks.py, safe_transaction_service/tokens/models.py, safe_transaction_service/tokens/tasks.py
- Add timeouts for contract/token tasks
- Add timeout for token list GET HTTP request
- Set version v4.20.2
=> Add timeouts for contract/tokens tasks

safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_views.py
Closes #1521 
Default value for safe address was missing
=> Add default value for delegates serializer

safe_transaction_service/history/tests/test_views.py
- Detects issues with swagger breaking
- Related to #1531
=> Add swagger test

safe_transaction_service/__init__.py, safe_transaction_service/contracts/tx_decoder.py, safe_transaction_service/history/tasks.py, safe_transaction_service/history/tests/test_tasks.py, safe_transaction_service/utils/tasks.py
- Currently a full reindex was triggered
- It can interfere with reorgs
=> Reindex until next issue

safe_transaction_service/history/views.py
- If chain is not defined in EthereumNetwork, -1 was returned
=> Return correct chainId on About RPC view

safe_transaction_service/__init__.py, safe_transaction_service/history/indexers/erc20_events_indexer.py, safe_transaction_service/history/indexers/internal_tx_indexer.py, safe_transaction_service/history/indexers/proxy_factory_indexer.py, safe_transaction_service/history/indexers/safe_events_indexer.py, safe_transaction_service/history/services/index_service.py
- We were using the indexer singletons for reindexing
- It can interfere with regular indexing, for example by disabling the address filters
- I'm in a high percentage sure this is the indexing issue we have been trying to fix for a while
=> Fix indexing issues

safe_transaction_service/history/indexers/ethereum_indexer.py
Closes #1565 
Add requests.ReadTimeout exception to back to process limit 1 when this happens.
=> Fix ReadTimeout getting blocks

safe_transaction_service/safe_messages/views.py
=> Add documentation for create messages swagger

safe_transaction_service/utils/tasks.py
- For some tasks we use Redis Locks to prevent 2 celery workers executing the same task
- Previously, we waited 1 second to get the Lock (in case it was taken) before failing
- During that second, every 0.1 second the Lock was checked again
- So every time a Lock was taken 10 queries were done to Redis, instead of 1
- With the new solution Lock will return inmediately if the Lock is taken
=> Make locks not blocking on tasks

gunicorn.conf.py, gunicorn_custom_workers.py, safe_transaction_service/__init__.py
- Closes #439
- Refactor gunicorn configuration to be set via envvar
=> Make timeouts work in gunicorn

.github/workflows/python.yml
=> Fix coveralls

safe_transaction_service/__init__.py
- https://github.com/safe-global/safe-transaction-service/pull/1616
- https://github.com/safe-global/safe-transaction-service/pull/1575
=> Set version v4.24.0

safe_transaction_service/tokens/clients/kucoin_client.py, safe_transaction_service/tokens/services/price_service.py
[safe-deployments PR](https://github.com/safe-global/safe-deployments/pulls) and check network name
exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py)
Adding Fantom FTMUSD price with Kucoin client for already added networks:
EthereumNetwork.FANTOM_OPERA
EthereumNetwork.FANTOM_TESTNET
https://github.com/safe-global/safe-eth-py/pull/609
https://github.com/safe-global/safe-deployments/pull/243
=> Add Fantom network FTM-USD Kucoin client price

safe_transaction_service/history/services/safe_service.py
Data is in ethereumTx not in InternalTx. 
Close #1650
=> Fix wrong variable

safe_transaction_service/__init__.py
=> Set version 4.25.1

requirements.txt, safe_transaction_service/__init__.py
=> Set version v4.26.1

safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tests/test_index_service.py
=> Consider RPC connection errors as out of sync

safe_transaction_service/contracts/management/commands/update_safe_contracts_logo.py, safe_transaction_service/contracts/tests/test_commands.py
Fix issue with not deployed versions on some networks.
=> Fix update_safe_contracts_logo command

requirements.txt, safe_transaction_service/__init__.py, safe_transaction_service/history/tests/test_commands.py
- Bump safe-eth-py to v6.0.0b4 and adjust tests
- Set version 4.27.0
=> Set version 4.27.0

safe_transaction_service/__init__.py, safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_models.py, safe_transaction_service/history/tests/test_views.py
=> Fix delegate retrieval when posting tx

safe_transaction_service/history/management/commands/check_index_problems.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/tests/test_commands.py, safe_transaction_service/history/tests/test_proxy_factory_indexer.py
Closes #1711 
- Add batch-size option
- Add test for `check_index_problems` 
- Fix `_reindex` wasn't reaching the last block
=> Add batch-size option

docker/web/Dockerfile, docker/web/Dockerfile_alpine, docker/web/celery/worker/run.sh
=> Run django on docker image as non root

.dockerignore
- Remove `vscode` and `github` folders from docker image
=> Remove not needed folders from docker image

docker/web/Dockerfile, docker/web/Dockerfile_alpine
- https://stackoverflow.com/a/77089706
- https://stackoverflow.com/a/66367783/724991
=> Fix kubernetes not detecting non numeric users

safe_transaction_service/safe_messages/models.py, safe_transaction_service/safe_messages/serializers.py, safe_transaction_service/safe_messages/tests/test_views.py
- Refactor signature validation to prevent code duplication
=> Fix 1271 signature validation for messages

safe_transaction_service/safe_messages/tests/test_views.py
=> Fix min length value in test

safe_transaction_service/contracts/management/commands/update_safe_contracts_logo.py, safe_transaction_service/contracts/tests/test_commands.py
=> Set by default MultiSendCallOnly as trusted for delegates

safe_transaction_service/safe_messages/serializers.py, safe_transaction_service/safe_messages/tests/factories.py, safe_transaction_service/safe_messages/tests/test_models.py, safe_transaction_service/safe_messages/tests/test_views.py, safe_transaction_service/safe_messages/utils.py
=> Fix 1271 signatures for messages

safe_transaction_service/history/filters.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/views.py
- Currently all txs were returned in multisig-txs endpoint
=> Only return trusted multisig txs by default

requirements.txt, safe_transaction_service/__init__.py, safe_transaction_service/tokens/clients/coingecko_client.py, safe_transaction_service/tokens/migrations/0010_tokenlist.py
Bump safe-eth-py to 6.0.0b15
Set version v4.32.1
=> Missing Base Sepolia address

.github/workflows/cla.yml
=> Fix CLA url

docker/web/celery/worker/run.sh
https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT
=> Disable database statement timeout during migrations

requirements.txt
Reverts safe-global/safe-transaction-service#1915
=> Revert "Bump django-filter from 23.5 to 24.1"

requirements.txt
Reverts safe-global/safe-transaction-service#1934
=> Revert "Revert "Bump django-filter from 23.5 to 24.1""

requirements.txt
=> Pin asgiref version to the previous one

safe_transaction_service/account_abstraction/services/aa_processor_service.py, safe_transaction_service/account_abstraction/tests/services/test_aa_processor_service.py
- Improve test to detect SafeConfirmation creation issues
=> Fix typo on confirmation indexing

safe_transaction_service/account_abstraction/serializers.py, safe_transaction_service/account_abstraction/tests/test_views.py
- It doesn't make sense to store `SafeOperations` that will never be valid
=> 4337: Check `valid_until` is newer than current timestamp

safe_transaction_service/account_abstraction/tests/services/test_aa_processor_service.py
=> Don't require 4337 Bundler RPC for tests

safe_transaction_service/account_abstraction/serializers.py, safe_transaction_service/account_abstraction/tests/test_views.py
- 4337 Bundlers receive parameters `paymasterAndData` together
- We decided to use the same approach to prevent confusing clients
=> 4337: Parse `paymasterAndData` together as in the Bundler API

safe_transaction_service/account_abstraction/services/aa_processor_service.py
In some cases UserOperation `initCode` is executed but `callData` execution fails, so Safe is deployed but no SafeOperation was executed
=> Index partially reverted UserOperations

requirements.txt, safe_transaction_service/account_abstraction/services/aa_processor_service.py, safe_transaction_service/account_abstraction/tests/services/test_aa_processor_service.py
- It changes a lot of logic and it's not fully supported in other networks but Sepolia
- We should wait to implement #2011
=> 4337: Ignore UserOperations for v0.7.0 entrypoint

safe_transaction_service/tokens/models.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_tasks.py
=> Process ENS names in tokenlist address fields

safe_transaction_service/history/indexers/safe_events_indexer.py
- Any user emitting a `SafeMultiSigTransaction` with a wrong payload on `additionalInfo` can hang the indexer
- Add more debug logs for the future
=> Handle decoding errors

safe_transaction_service/history/indexers/safe_events_indexer.py
- Currently is logged as bytes
=> Fix logging tx-hash in a proper hex format

safe_transaction_service/account_abstraction/services/aa_processor_service.py
- Nonce is increased, so they must be returned by tx service.
- Related to #2035.
=> 4337: Index reverted UserOperations

safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/urls.py, safe_transaction_service/history/views.py
- `master-copies/` -> `singletons/`
- `transactions/` -> `multisig-transactions/`
=> Remove deprecated endpoints

safe_transaction_service/__init__.py
- 4337 indexing is a change big enough to bump the major version
=> Set version 5.0.0

safe_transaction_service/account_abstraction/models.py, safe_transaction_service/account_abstraction/serializers.py, safe_transaction_service/account_abstraction/tests/factories.py, safe_transaction_service/account_abstraction/tests/test_models.py, safe_transaction_service/account_abstraction/tests/test_views.py, safe_transaction_service/account_abstraction/urls.py, safe_transaction_service/account_abstraction/views.py, safe_transaction_service/history/tests/test_views.py
=> 4337: Add endpoint to add signatures to an existing SafeOperation

safe_transaction_service/history/tasks.py
=> Expose explicitly when transaction service is synced

requirements.txt
=> Bump requests to v2.32.3

safe_transaction_service/history/tests/test_collectibles_service.py
- Fixed collectibles ENS test, it seems to be falling and snowballing problems in other tests
=> Fix ENS cannot be resolved in collectibles test

safe_transaction_service/account_abstraction/views.py, safe_transaction_service/contracts/views.py, safe_transaction_service/history/views.py, safe_transaction_service/history/views_v2.py, safe_transaction_service/safe_messages/views.py, safe_transaction_service/tokens/views.py
Closes https://github.com/safe-global/safe-transaction-service/issues/2071
The new description of the endpoints is based on the [Notion page](https://www.notion.so/safe-global/API-Docs-endpoints-6ad1010e37264af29be286d65625095e), written by the Dev Experience Team.
=> Update endpoints swagger description

config/settings/base.py, safe_transaction_service/history/helpers.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/tests/test_views_v2.py
Closes #2081
- Adds support for signatures of EIP-712 payloads which might not include the Chain ID.
- Signatures of payloads which included the Chain ID are still valid.
=> Allow cross chain Delegate registration

safe_transaction_service/account_abstraction/serializers.py
- Previously, if a Safe was not deployed no more confirmations were allowed.
- After this PR the owners encoded in the `initCode` will be checked if the Safe is not deployed.
=> 4337: Allow confirmations for not initialized Safes

safe_transaction_service/history/services/balance_service.py
Reverts: https://github.com/safe-global/safe-transaction-service/pull/2132 and https://github.com/safe-global/safe-transaction-service/pull/2133
=> Revert "Add logger to cache key in get balances"

requirements.txt, safe_transaction_service/account_abstraction/serializers.py, safe_transaction_service/account_abstraction/services/aa_processor_service.py, safe_transaction_service/contracts/management/commands/update_safe_contracts_logo.py, safe_transaction_service/contracts/services/contract_metadata_service.py, safe_transaction_service/history/admin.py, safe_transaction_service/history/indexers/tx_processor.py, safe_transaction_service/history/management/commands/fix_ethereum_logs.py, safe_transaction_service/history/management/commands/fix_ethereum_txs.py, safe_transaction_service/history/management/commands/send_slack_notification.py, safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/history/migrations/0036_fix_exec_from_module.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/balance_service.py, safe_transaction_service/history/services/collectibles_service.py, safe_transaction_service/history/services/index_service.py, safe_transaction_service/history/services/reorg_service.py, safe_transaction_service/history/services/safe_service.py, safe_transaction_service/history/services/transaction_service.py, safe_transaction_service/history/tests/test_collectibles_service.py, safe_transaction_service/history/views.py, safe_transaction_service/safe_messages/serializers.py, safe_transaction_service/safe_messages/utils.py, safe_transaction_service/tokens/management/commands/add_token.py, safe_transaction_service/tokens/management/commands/update_tokens_from_coinmarketcap.py, safe_transaction_service/tokens/migrations/0002_auto_20200903_1045.py, safe_transaction_service/tokens/models.py, safe_transaction_service/tokens/tasks.py, safe_transaction_service/utils/ethereum.py, safe_transaction_service/utils/serializers.py
- Related to https://github.com/safe-global/safe-eth-py/pull/1209
=> Migrate from `EthereumClientProvider`

requirements.txt
Reverts safe-global/safe-transaction-service#2161
=> Revert "Bump web3 from 6.20.0 to 6.20.1"

safe_transaction_service/history/services/transaction_service.py, safe_transaction_service/history/signals.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/views.py
Reopens #2188 
- The solution of adding cache didn't solve the problem.
=> Revert "Add cache to all-transactions endpoint (#2190)"

safe_transaction_service/__init__.py, safe_transaction_service/history/services/transaction_service.py
- Add configurable cache, previously was hardcoded to 1 hour
- Bump version to v5.8.2
=> Add configurable cache to all_transactions

safe_transaction_service/history/services/transaction_service.py
Uses `zlib` to compress the data stored in cache.
=> Add zlib compression for transactions cache

config/settings/base.py, safe_transaction_service/history/services/transaction_service.py
- Add configurable compression level
- Disabling compression by default
=> Add configurable compression level

safe_transaction_service/__init__.py, safe_transaction_service/history/tasks.py
=> Only set processed the not processed InternalTxDecoded

requirements.txt
Reverts safe-global/safe-transaction-service#2248
=> Revert "Unpin asgiref"

config/settings/base.py, safe_transaction_service/history/services/notification_service.py, safe_transaction_service/history/signals.py, safe_transaction_service/safe_messages/signals.py
=> Add configuration parameter to prevent building payloads for notifications/events

safe_transaction_service/contracts/tests/test_tx_decoder.py, safe_transaction_service/contracts/tx_decoder.py
=> Add decoding for fallback calls

docker/web/Dockerfile, docker/web/Dockerfile_alpine
Reverts safe-global/safe-transaction-service#2255
=> Revert "Bump python from 3.12-alpine to 3.13-alpine in /docker/web"

safe_transaction_service/tokens/tasks.py
- URLField allow 200 chars at max
=> Check `logoUri` size

safe_transaction_service/account_abstraction/filters.py, safe_transaction_service/account_abstraction/models.py, safe_transaction_service/account_abstraction/tests/test_views.py, safe_transaction_service/account_abstraction/views.py, safe_transaction_service/history/filters.py, safe_transaction_service/utils/filters.py
- Add also more filters
- Closes #2314
=> Add executed filter to SafeOperation

safe_transaction_service/history/indexers/erc20_events_indexer.py
- In ERC20Indexer, every chunk of addresses store them in cache
- It should not take any time, and in case task is interrupted during address loading it will be very useful, as loading can be restarted from that point
=> Store erc20 loaded addresses in cache

safe_transaction_service/history/indexers/tx_processor.py, safe_transaction_service/history/tests/test_tx_processor.py
=> Add exception when deactivating a non-enabled module

safe_transaction_service/__init__.py, safe_transaction_service/tokens/admin.py, safe_transaction_service/tokens/models.py
- Add admin page for `TokenNotValid`
- This is a hotfix, increase version to `5.13.1`
=> Fix race conditions when inserting tokens on `TokenNotValid`

safe_transaction_service/history/services/index_service.py
=> Increase logs for ethereum tx issue

safe_transaction_service/history/services/index_service.py
Reverts safe-global/safe-transaction-service#2337
=> Revert "Increase logs for ethereum tx issue"

safe_transaction_service/history/services/index_service.py
- Thanks to that log line we found out that the issue was on safe-eth-py
- It was already fixed on https://github.com/safe-global/safe-eth-py/pull/1439
=> Remove log for `Unexpected missing transaction`

requirements.txt
Reverts safe-global/safe-transaction-service#2357
=> Revert "Asgiref was pinned due to a problem with drf-yasg"

safe_transaction_service/contracts/management/commands/setup_safe_contracts.py
Enables SafeMigration contract for trusted for delegates.
=> Enable SafeMigration for trusted for delegates call

.github/workflows/python.yml, docker-compose.yml
=> Update to postgres 16

docker-compose.yml
=> Add missing worker queue to docker-compose

safe_transaction_service/history/management/commands/validate_tx_integrity.py, safe_transaction_service/history/tests/test_commands.py
- Validate integrity for `MultisigTransaction` and `MultisigConfirmation` in queue
=> Add command to validate integrity for multisig transactions in queue

safe_transaction_service/history/models.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/views.py, safe_transaction_service/history/views_v2.py
- Add logs to monitorize  creations of transactions
=> Add request logs

safe_transaction_service/history/exceptions.py, safe_transaction_service/history/serializers.py, safe_transaction_service/history/services/safe_service.py, safe_transaction_service/history/tests/test_safe_service.py, safe_transaction_service/history/tests/test_serializers.py, safe_transaction_service/history/tests/test_views.py, safe_transaction_service/history/tests/test_views_v2.py, safe_transaction_service/history/views.py, safe_transaction_service/history/views_v2.py
Don't validate response transactions which nonce is less than current nonce, so cannot be executed. 
Validates the owner of approveHash
=> Ignore response validation of non executed transactions with old nonces

README.md, docker/web/celery/worker/run.sh, safe_transaction_service/contracts/management/commands/setup_safe_contracts.py, safe_transaction_service/contracts/tests/test_commands.py
- Add flag to enable/disable setup contracts on startup
- Update trusted delegate calls
Closes #2436
=> Add flag to enable setup Safe contracts

safe_transaction_service/history/views_v2.py
- Move POST /api/v2/delegates/ from `transactions` section to `delegates` section
=> Fix swagger tag

safe_transaction_service/history/management/commands/setup_service.py, safe_transaction_service/history/tests/test_commands.py
=> Setup default singleton addresses if are deployed.

safe_transaction_service/contracts/management/commands/setup_safe_contracts.py, safe_transaction_service/contracts/tests/test_commands.py
=> Create default Safe contract deployments data if are deployed

safe_transaction_service/safe_messages/tests/test_views.py
=> Test contract signatures for 1.3.0 and 1.4.1 Safes

config/settings/base.py, safe_transaction_service/contracts/management/commands/index_contracts_with_metadata.py, safe_transaction_service/contracts/services/contract_metadata_service.py, safe_transaction_service/contracts/tasks.py, safe_transaction_service/contracts/tests/mocks/contract_metadata_mocks.py, safe_transaction_service/contracts/tests/services/test_contract_metadata_service.py, safe_transaction_service/contracts/tests/test_models.py
=> Deprecate EtherscanV1

safe_transaction_service/tokens/tasks.py, safe_transaction_service/tokens/tests/test_tasks.py
=> feat: Update token name and symbol from token lists
