docker/ganache/Dockerfile

**Description**
In the near future, we will integrate the tx-history-service following the PersonalSafe contracts approach.
Used here: https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafePersonalEdition.sol#L164
For doing it successfully we have to enable the **--noVMErrorsOnRPCResponse** flag in ganache, otherwise when we calculate the process of calculating needed gas on inner safe transactions will fail

Feature: Enable flag for not raise VM errors on RPC responses in ganache

---

safe_transaction_service/history/views.py

I updated the swagger doc and 422 error codes on endpoints that we will use in the first public release.
I think it makes sense to move `if not Web3.isChecksumAddress(address)` checks into a decorator.
I didn't change it in all other places.

update swagger and error codes in some places

---

safe_transaction_service/notifications/views.py

Fix for the 500 server error that happened when address was not specified.
```python
2020-08-11 09:35:55,797 [ERROR] [MainProcess] Internal Server Error: /api/v1/notifications/devices/799eb559-0128-4013-b356-f4c5f908cc06/safes/0x7348C4a88858Bc3E105150D50860FbcaA0327c2a/
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```

 fixed querying for safe address

---

requirements.txt
safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/models.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_commands.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/history/tests/test_tx_processor.py
safe_transaction_service/history/views.py

Signatures on v1.3.0 are not compatible with the ones on v1.2.0, so queued transactions became invalid when Safe master copy is updated.
- Remove new txs on master copy update when signing is invalid (updating/downgrading to/from `v1.0.0` or `v1.3.0`).
- Closes issue #260

Remove new txs on master copy update

---

safe_transaction_service/notifications/tasks.py

The `CONFIRMATION_REQUEST` notification was missing the `chainId` parameter that is present in other notifications.
As a result, the client can't find appropriate safe to show this notification.
Added the information similar to how it was added in the `history/signals.py`

Added chain id

---

requirements-dev.txt

- Remove `mypy` from `requirements-dev.txt`
- `mypy` is declared in both `requirements-dev.txt` and `requirements-test.txt`. Since `requirements-dev.txt` depends on `requirements-test.txt` this would lead to an error where duplicate dependencies were provided

Fix duplicate mypy requirment declaration

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py

- `signature` field now allows `null` values
- The `required` field made it so that if the `POST` payload did not have the `signature` key it would be valid but if it contained a `null` `signature` then it would fail ("value cannot be null")
**Before**:
```javascript
{
// no signature field == valid
}
```
```javascript
{
"signature": null // This fails! Signature was provided but it's null
}
```
**After**:
```javascript
{
// no signature field == valid
}
```
```javascript
{
"signature": null // null signature == valid
}
```

Allow signature field to be null in /multisig-transactions

---

safe_transaction_service/history/indexers/safe_events_indexer.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

Closes issue #348 
As multiple events can be emitted before the `SafeSetup` event (using custom `to` and `data` during Safe creation) `SafeSetup` event should be processed first

Fix setup modules

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py

I reminded that this attribute was present in DB and we were not returning it (cc @fmrsabino)

Add L2 attribute to master-copies endpoint

---

requirements.txt
safe_transaction_service/__init__.py

- Update Gnosis-py to v3.3.1 (use multicall)
- Improves `/balances` and `safe` information endpoints (related to #321)

Set version 3.2.0

---

requirements.txt
safe_transaction_service/__init__.py

Balances were not working on networks without multicall (like VOLTA)

Fix batch call issue on networks without multicall

---

docker/web/Dockerfile

Install wheel before other dependencies when building the docker image. If not, wheel packages cannot be used

Install wheel before other dependencies

---

safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/views.py

- Add support for native coin fiat price in ` /tokens/<address>/price/usd`
- In order to retrieve the native coin of the chain tied to this service, the address to be used should be `0x0000000000000000000000000000000000000000` so from the client perspective the endpoint path would be `/tokens/0x0000000000000000000000000000000000000000/price/usd`
- If an error occurs when fetching the new price, `0` is returned instead. This is line with the other token prices results in case of failure.

Add support for native coin to /tokens/price/usd

---

manage.py
requirements.txt
run_tests.sh
safe_transaction_service/history/tests/utils.py
safe_transaction_service/tokens/services/price_service.py

- Closes #384 
- Also sets the default env file for manage.py and increases sleep time in `run_tests.py.` Let me know if you want it as a separate PR
- Adds EnzymeOracle from gnosis-py 3.4.0 to composed price oracles.
Waiting for https://github.com/gnosis/gnosis-py/pull/87 to be merged

Feature: Add enzyme oracle to composed price oracles

---

config/settings/base.py

Application was not compatible with nginx paths. Now `FORCE_SCRIPT_NAME` can be set as an environment variable to add a base path for all the project
@fmrsabino this must be implemented also in the `config-service` so @jpalvarezl can use it in `safe-infrastructure`

Add force script name for nested paths on nginx

---

docker/web/celery/worker/run.sh
docker/web/run_web.sh

Only one worker is fired up, so there are no problems of concurrent workers running as it happens with the web pod

Do migrations on the worker

---

.github/workflows/python.yml

Coveralls is not working, `COVERALLS_REPO_TOKEN` is not needed anymore
Don't use `COVERALLS_REPO_TOKEN`

Fix coveralls

---

.github/workflows/python.yml
safe_transaction_service/history/admin.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_erc20_events_indexer.py
safe_transaction_service/history/tests/test_models.py

Sometimes ERC721 don't follow the standard `Transfer` event, not indexing the `tokenId`. Now when processing every event the token address will be check for `decimals`

Tell apart ERC20/ERC721 looking at token contract

---

safe_transaction_service/__init__.py
safe_transaction_service/history/models.py
safe_transaction_service/history/views.py

- Use SQL `UNION ALL` instead of `UNION`
- `UNION` checks for duplicates and it's orders of magnitude less optimal for big queries than `UNION ALL`

Optimize transfers query

---

safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py

Don't reindex until the current block, only until the next not problematic transaction

Set reindexing limit

---

safe_transaction_service/__init__.py
safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py
safe_transaction_service/utils/tasks.py

Reindexing of missing transactions were overloading the service
- Only one reindexing is allowed at a time now. It should be enough for quickly fix all the problematic Safes
- Database event pool is always closed, even if an exception occurs
- `safe_transaction_service.history.tasks.process_decoded_internal_txs_task` will only be called every 20 minutes. The task is already called every time a new trace appears either way and the scheduled task is only to make sure everything was processed, so no need to be biminutely

Only one reindexing time

---

safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/urls.py
safe_transaction_service/history/views.py

- `/about/ethereum-rpc/`
- `/about/ethereum-tracing-rpc/`
```json
{
"version": "EthereumJS TestRPC/v2.13.2/ethereum-js",
"block_number": 70,
"chain_id": 1337,
"chain": "GANACHE",
"syncing": false
}
```

Add endpoints for Ethereum RPC info

---

safe_transaction_service/history/management/commands/setup_service.py

Gnosis is not officially supporting Boba Network, but I'd rather keep on deploying your tags rather than maintain our fork. 
Not sure if this is OK or not?
Add Boba deterministic deployments.

Support Boba Network contracts

---

requirements.txt
safe_transaction_service/__init__.py

- Bump gnosis-py from 3.7.2 to 3.7.4 – https://github.com/gnosis/gnosis-py/compare/v3.7.2...v3.7.4 – this includes the fix to the `mulitcall2` address for `Avalanche`
- Bump service version from 3.4.15 to 3.4.16

Bump gnosis-py from 3.7.2 to 3.7.4

---

safe_transaction_service/history/services/index_service.py

- `EthereumBlock.objects.create_from_block` has a keyword argument named `confirmed` (used as `cofirmed` which is a typo)

Fix keyword argument typo in IndexService

---

config/settings/local.py

What was wrong?
If a docker compose setup is used for all needed services supporting Gnosis Safe, the transaction service would reject requests coming from other hosts.
Closes #
How was it fixed?
Flexible DJANGO_ALLOWED_HOSTS
https://github.com/gnosis/safe-transaction-service/pull/530

flexible allowed hosts for docker compose

---

safe_transaction_service/tokens/migrations/0004_ethereum_address_field_v2_20211201_1512.py

Token address migration was only casting `varchar` instead of converting to `bytea`

Fix token migration

---

config/settings/base.py
docker/web/celery/worker/run.sh
safe_transaction_service/__init__.py

- Concurrency was too low (`120`) to process all the needed tasks. A higher number can be used as we are using `gevent` (light threads)
- Make concurrency configurable so we can adjust it without a deployment
- Set `500` as a default for concurrency (x5)
- Increase `CELERY_BROKER_POOL_LIMIT` as stated here: https://docs.celeryproject.org/en/stable/userguide/optimizing.html#broker-connection-pools

Fix celery concurrency

---

safe_transaction_service/contracts/migrations/0008_ethereum_address_field_v2.py

Contract `address` was casted as `text` instead of converted to `bytea`

Fix contracts migration

---

safe_transaction_service/history/services/balance_service.py
safe_transaction_service/history/tests/clients/test_ens_client.py
safe_transaction_service/history/tests/test_balance_service.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tasks.py
safe_transaction_service/tokens/tests/test_price_service.py
safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/views.py

- When providing `0x00.00` on `tokens/<address>/prices/usd/ fiat value for the native coin was not retrieved

Fix native coin price on token fiat endpoint

---

config/settings/base.py
safe_transaction_service/history/tasks.py

- There were deadlocks on DB access (detected on production xDai)
- Number of max connections to the database was reduced to `4` when there were performance issues on DB level, so DB woulnd't get overloaded. Now we can safetely increase it again.
- Increase number of DB `MAX_CONNS` from 4 -> 50
- A task was not closing DB connections, it was fixed
- `MAX_CONNS` and `REUSE_CONNS` are now configurable via environment var

Increase number of DB `MAX_CONNS` from 4 -> 50

---

scripts/deploy_docker.sh

Some people just want to get the service updated without having to manually update the version
Setting the `latest` tag on Dockerhub, as a lot of projects do

Push `latest` tag to Dockerhub when deploying a version

---

docker/web/Dockerfile
requirements.txt

https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary

Use psycopg2 instead of psycopg2-binary

---

safe_transaction_service/__init__.py
safe_transaction_service/history/views.py

- When using a serialiser we should call `.is_valid()` before accessing it via `Response`

Remove serializer validation when ENABLE_OWNERS_ENDPOINT is false

---

config/settings/base.py
safe_transaction_service/utils/tests/test_loggers.py

- In order to collect more data on the tasks' execution, the `IgnoreSucceededNone` filter should be disabled
(We will be testing this on staging before making a decision if this should be pushed to production or be behind an additional runtime configuration parameter)

Disable IgnoreSucceededNone filter

---

README.md
config/settings/base.py
safe_transaction_service/__init__.py
safe_transaction_service/history/admin.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- `OwnersView` now requires authentication via a `Token`
- This `Token` should be set for users who want to access this endpoint (this can be done via the admin interface)
- Given a valid token `example-token`, the token can be used by adding the following header to the request for this endpoint: `Authorization: Token example-token`
- Unauthenticated requests return a `401`
- Reverted changes made for releases `3.4.22`, `3.4.23` and `3.4.24`. For comparison this is the diff between `3.4.21` and the upcoming release https://github.com/gnosis/safe-transaction-service/compare/v3.4.21...use-token-auth

Require token auth for OwnersView

---

config/settings/base.py
safe_transaction_service/utils/tests/test_loggers.py

- Add Celery `IgnoreSucceededNone` filter again
- Make it configurable depending on the `DEBUG` flag

Revert remove of IgnoreSucceededNone log filter

---

README.md
config/settings/base.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- `OwnersView` no longer requires authentication
- Tokens can still be created as before (the API token feature was not removed)

Disable authentication in OwnersView

---

config/settings/base.py
safe_transaction_service/history/services/collectibles_service.py
safe_transaction_service/history/tests/test_collectibles_service.py

Ipfs addresses can be ipfs://hash or ipfs://ipfs/hash. Both ways will be converted to the same http url

Normalize IPFS addresses when using HTTP gateway

---

config/settings/base.py
safe_transaction_service/contracts/tasks.py
safe_transaction_service/history/signals.py
safe_transaction_service/history/tests/test_signals.py

Regular priority for Celery is 3, we are setting 1 for these tasks (the lowest the less priority)
This is a first fix for #620

Set low priority for webhook/notification tasks

---

safe_transaction_service/history/tasks.py

- Updated from 10 -> 100 concurrent connections
- Related to #620, as a long of tasks were webhooks calls waiting

Increase connection pool for webhook HTTP requests

---

safe_transaction_service/tokens/models.py
safe_transaction_service/tokens/tests/test_models.py

Fix parsing when Token name/symbol are bytes

---

requirements.txt
safe_transaction_service/__init__.py
safe_transaction_service/history/services/collectibles_service.py

- For some ERC721 tokens there's an error retrieving the uri that makes the service crash
- Updating gnosis-py to the last version

Fix ERC721 token uris error

---

config/settings/base.py

- There wasn't a way to see queries/responses to/from ethereum nodes
- Closes #434
- Log queries/responses to/from ethereum nodes

Show queries to ethereum nodes when enabling DEBUG

---

config/settings/production.py

Support for CSRF trusted origins https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-trusted-origins
which is useful for different kinds of deployments.
Relevant: 
https://github.com/gnosis/safe-config-service/pull/402
https://github.com/gnosis/safe-transaction-service/issues/640
Closes #
Added reading env CSRF_TRUSTED_ORIGINS and setting CSRF_TRUSTED_ORIGINS.  

support for trusted csrf origins

---

config/settings/production.py

- Use Django default https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins

Make CSRF_TRUSTED_ORIGINS default [] instead of [""]

---

safe_transaction_service/contracts/migrations/0007_contract_trusted_for_delegate_call.py

Don't trust old multisend contracts. They allow nested delegate calls

Fix trusted delegate calls migration

---

safe_transaction_service/contracts/tests/test_tx_decoder.py
safe_transaction_service/contracts/tx_decoder.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/views.py

- When there's an ABI function selector colliding, sometimes a wrong decoder is used
- Closes #638
Refactor `SafeTxDecoder`:
- Add a method `get_abi_function` to get the proper abi for data and an optional contract `address`.
- Pass always the `contract address` with the `data` to be decoded
Refactor `DbTxDecoder`:
- If the contract address has an ABI on database and can decode the `data` it will be used first 
Add `to` for the data decoding endpoint

Refactor tx decoder

---

docker/web/celery/worker/run.sh

- Configurable via WORKER_MAX_MEMORY_PER_CHILD environment variable
- Closes #657

Set celery max_memory_per_child to 2GiB

---

requirements.txt
safe_transaction_service/__init__.py

- Update redis to v4.1.2
- Set version 4.0.2
There's a memory leak on production services that we don't observe on staging. The only difference is the redis version
Update redis

Fix memory leaks (update redis)

---

requirements.txt

- Remove `pyethereum` dependency, as it's not needed anymore

Bump gnosis-py to v3.8.0

---

safe_transaction_service/__init__.py
safe_transaction_service/contracts/views.py

- When redis cache backend is used response should be returned after calling `add_post_render_callback`. [More info](https://docs.djangoproject.com/en/4.0/ref/template-response/#django.template.response.SimpleTemplateResponse.add_post_render_callback)

Fix contract caching error

---

.gitignore
.vscode/launch.json
.vscode/settings.json

- Running/debugging tests should be working
- `.vscode` folder is excluded on `.gitignore` as this is the basic template but it needs to be modified by the user, e.g. adding information about Python environment. That will be done by `vscode` run running it for the first time

Add Vscode default configuration

---

safe_transaction_service/history/views.py
safe_transaction_service/tokens/views.py

- That way, context can be injected and used on the serializer

Use `get_serializer` instead of `serializer_class`

---

config/settings/base.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/test_index_service.py

- If less than 10% of contracts are out of sync for ERC20/ERC721, consider service synced
- That will prevent a lot of alerts when only one new or two contracts are out of sync

Be less restrictive when setting service out of sync

---

safe_transaction_service/history/tasks.py

- We are using `full_url` if the Webhook called failed with an error status – we should use `base_url` so that the token is not logged

Redact token value from hook logs

---

config/settings/local.py
config/settings/production.py
requirements.txt

- Bump django from 3.2.11 to 4.0.2
- Remove not needed django-redis

Bump Django to v4

---

config/settings/local.py
config/settings/production.py
requirements.txt

Celery is not working well without `django-redis`. I think the best solution for now is downgrade to Django v3 until celery/celerybeat release proper support for Django v4

Revert "Bump Django to v4 (#709)"

---

safe_transaction_service/history/admin.py

- There was a parsing error due to `block_number` receiving a string value if `block_hash` was provided
- Even if it's desired to be able to filter using the 2 fields, `block_hash` was removed from the search

Fix EthereumBlock search on admin

---

safe_transaction_service/history/admin.py
safe_transaction_service/utils/admin.py

- When trying to search for a field using a string in the admin field, there was an error 500
- For example, if searching for a `blockHash` there was an error when trying to format the string to a integer

Fix admin search for integer fields

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py

- Trusted gives information about the transaction. Transaction will be trusted if at least one owner of the Safe signed it, it's executed or someone with enough privileges created it

Return `trusted` as part of the MultisigTransaction

---

safe_transaction_service/notifications/tasks.py

- Owners were notified again if a delegate was set due to a typo

Don't notify owner again if it has a delegate set

---

safe_transaction_service/history/tests/clients/test_ens_client.py
safe_transaction_service/tokens/models.py

- Make sure ERC20 are not indexed as ERC721 because of a node indexing issue
- Fix broken ENS test

Fix ERC20/721 indexing

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/tests/test_safe_events_indexer.py
safe_transaction_service/history/tests/test_tx_processor.py

- Guarantee we keep owners in the database in the same order they are kept in blockchain
- Closes #814

Maintain order for owners when adding/removing/swapping

---

safe_transaction_service/history/signals.py
safe_transaction_service/history/tests/test_signals.py

- Previously, if reindexing all the webhooks are sent again
- With this change webhooks older than 60 minutes are ignored

Don't send webhooks older than 60 minutes

---

docker/web/celery/worker/run.sh

- Redis was not able to handle them, but RabbitMQ is

Allow 1000 tasks running

---

config/settings/base.py

- It should be equal to the concurrent tasks running

Increase celery pool broker limit

---

safe_transaction_service/__init__.py
safe_transaction_service/history/tests/clients/test_ens_client.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- Get SafeInfo from blockchain (instead of `SafeLastStatus` table) if `nonce=0` or not found on the DB.
- Fixes issues with Safes not indexed or not L2 Safes in L2 networks

Get SafeInfo from blockchain if nonce=0

---

safe_transaction_service/history/tasks.py

- Sometimes there are a lot of webhooks and tasks need to wait for the pool to be free

Increase webhook connection pool

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/signals.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_safe_events_indexer.py

- This was a very old behaviour that makes database struggle and leave some unbinded traces on DB without processing
Also:
- Add more debug information for tx processing
- Refactor code and rename variables
- Use iterator for InternalTxDecoded

Don't require Safes to be "indexed" to be processed

---

safe_transaction_service/__init__.py
safe_transaction_service/history/admin.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

We are sorting traces using `blockNumber`, `transactionIndex` and `traceAddress` (for L2 Safes `traceAddress=logIndex`), but as the field is a `varchar`, sorting is not working as supposed. Example of current ordering:
| Safe Address | Trace Address | Safe Nonce |
| ------------- | ------------- | ------------- |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 0 | 37 |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 12 | 41 |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 15 | 42 |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 18 | 43 |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 3 | 38 |
| 0x2de145a14e19618d4cb11201e56b6e84386f41942f6cbbf0dc4c1e6d649ead8b | 6 | 39 |
| …

Sort traces by internal_tx_id

---

safe_transaction_service/__init__.py
safe_transaction_service/history/indexers/ethereum_indexer.py

- Fix typo on EthereumIndexer
- Set version 4.3.5

Fix typo on EthereumIndexer

---

safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- Modifies master copy endpoint
- Don't return not L2 MasterCopies on L2 networks

Return only relevant master copies

---

safe_transaction_service/__init__.py
safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/notifications/tasks.py

- When a reorg happens, `SafeLastStatus` was deleted
- If `SafeLastStatus` was missing, indexing was not able to continue
- Now when `SafeLastStatus` is not found `SafeStatus` will be used to recreate it if possible
- Set version 4.3.6 as this needs to be released asap

Fix indexing issues due to SafeLastStatus missing

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/notifications/tasks.py

- There's no need to override Django ORM method

Rename SafeLastStatus get_or_create -> get_or_generate

---

config/settings/base.py
docker-compose.yml
docker/web/celery/worker/run.sh

Multiple queues were created:
- contracts
- indexing
- notifications
- tokens
- webhooks
Added a new variable `RUN_MIGRATIONS` to choose what worker will run the database migrations.
Closes #620

Split Celery tasks in queues

---

gunicorn.conf.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/utils/tasks.py

- There's no need on checking for checksum addresses on the indexer, and it takes some time.
Also, being a CPU intensive task locks all the other threads

Remove gevent locks

---

safe_transaction_service/history/views.py

The endpoint `POST ​/safes​/{address}​/multisig-transactions​/` in Swagger shows this error message when the response code is 422: `Invalid ethereum address/User is not an owner/Invalid safeTxHash/Invalid signature/Nonce already executed/Sender is not an owner`
`Sender is not an owner` should be replaced with `Sender is not an owner or delegate`.
Message error was updated.

Mention delegates in error message when creating a new tx

---

safe_transaction_service/history/management/commands/setup_service.py

Godwoken Testnet missing.
Godwoken Testnet added based on addresses from safe-deployments.

feat: add godwoken testnet

---

safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/indexers/events_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py

Prevent issues with nodes returning a maximum number of events, so some events are missed
- Get ERC20 events in parallel and using the address filter, instead of getting every erc20 event and checking if it is on our list of addresses.
- Refactor EventsIndexer

Refactor erc20 indexing

---

.vscode/launch.json
safe_transaction_service/contracts/tests/test_admin.py
safe_transaction_service/tokens/tests/test_admin.py

Some tests were producing avoidable warnings.
I changed some initialisations in the admin tests to avoid the warnings.

Fix warnings in admin tests

---

config/settings/base.py
safe_transaction_service/history/services/collectibles_service.py
safe_transaction_service/history/tests/test_collectibles_service.py

- Increase timeout from 10 -> 15 seconds
- Remove ipfs.io as secondary IPFS for tests

Use ipfs.io as the default IPFS gateway

---

safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/views.py

The service wasn't handling properly errors coming from price providers, `500 HTTP` code was being returned to the client when a price fetch failed.
Closes #972
This kind of exceptions are now catch, a `503 HTTP` code is sent to the client with a more user friendly message.

Handle exception when retrieving prices

---

config/settings/base.py
safe_transaction_service/__init__.py
safe_transaction_service/history/indexers/events_indexer.py

- 0 (no limit) was set by mistake and had to be modified on the deployment via envvar

Set 5000 addresses as default for calling `eth_getLogs`

---

safe_transaction_service/history/management/commands/setup_service.py

Missing safe contract addresses for Klaytn network
Added safe contract addresses for Klaytn Mainnet and Testnet
Ref: 
**Safe address :** 
Baobab Testnet : [0xfb1bffC9d739B8D520DaF37dF666da4C687191EA](https://baobab.scope.klaytn.com/account/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA?tabId=internalTx)
Cypress Mainnet : [0xfb1bffC9d739B8D520DaF37dF666da4C687191EA](https://scope.klaytn.com/account/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA?tabId=internalTx)
**Proxy Factory :** 
Baobab Testnet : [0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC](https://baobab.scope.klaytn.com/account/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC?tabId=internalTx)
Cypress Mainnet : [0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC](https://scope.klaytn.com/account/0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC?tabId=internalTx) …

add klaytn network

---

config/settings/base.py

- `CORS_ORIGIN_ALLOW_ALL` was renamed to `CORS_ALLOW_ALL_ORIGINS`
- More info: https://github.com/adamchainz/django-cors-headers

Fix CORS configuration

---

.env.test
.github/workflows/python.yml
safe_transaction_service/contracts/models.py
safe_transaction_service/contracts/tasks.py
safe_transaction_service/contracts/tests/test_tasks.py
safe_transaction_service/history/admin.py
safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

- Improve contract testing
- Replace NOT IN queries for EXIST (https://stackoverflow.com/questions/173041/not-in-vs-not-exists)
- Task is run every 6 hours and only for last day transactions, to prevent overloading the service
- Closes #992

Search for contract ABIs inside Multisend calls

---

safe_transaction_service/history/management/commands/setup_service.py

- This task was created when we were indexing Safe addresses one by one and some of them missed sync while others were syncing
- As we are indexing erc20 events in big batches, I think this task is not needed anymore and can only cause conflicts with the regular indexing task, as this task is called once every 5 minutes and has no limit on how many times can be spammed. It can always be called from manage.py

Disable index_erc20_events_out_of_sync_task scheduled task

---

safe_transaction_service/history/management/commands/setup_service.py

Mikomeda Cardano testnet was missing
Added Milkomeda Cardano testnet addresses from the safe-deployments repo (https://github.com/safe-global/safe-deployments/pull/97)

Add milkomeda cardano testnet

---

safe_transaction_service/history/apps.py

- Previously it was needed, as loading tx decoder could take more than a minute
- With the current implementation it takes a few seconds, so only the first request will be delayed a little until it gets cached

Don't preload tx decoder

---

safe_transaction_service/history/management/commands/setup_service.py

Mikomeda Cardano mainnet was missing
Added Milkomeda Cardano mainnet addresses from the safe-deployments repo (https://github.com/safe-global/safe-deployments/pull/103)

Add Milkomeda cardano mainnet

---

safe_transaction_service/history/views.py

Closes #847 
Add `["execution_date", "safe_nonce", "block", "created"]`  to `ordering_fields`.

Add `created` to ordering fields for all-transactions

---

safe_transaction_service/history/management/commands/setup_service.py

Missing safe contract addresses for Venidium Mainnet network
updated [setup_service.py](https://github.com/safe-global/safe-transaction-service/compare/master...Venidium-Network:safe-transaction-service:master#diff-2fe58867936fddcf0364a8394de2efbd6dc48c4a19b34787112191a67f5b1e63)

add venidium safe contracts

---

safe_transaction_service/history/management/commands/setup_service.py

Configurations for Arbitrum Nova was missing
Depends on https://github.com/safe-global/safe-eth-py/pull/328

Add ARBITRUM_NOVA

---

safe_transaction_service/tokens/clients/binance_client.py
safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tests/test_price_service.py

Milkomeda-wrapped Cardano tokens had incorrect prices on a custom network.
Added Cardano pricing.

Add price calculation of milkomeda C1 tokens

---

requirements-dev.txt
requirements.txt

- It has very useful commands, like shell_plus
- Closes #1028

Move django-extensions from requirements-dev to requirements

---

safe_transaction_service/history/management/commands/setup_service.py

The cronos mainnet address for v1.3.0 l2 was not right. 
Check out the address in safe deployments: https://github.com/safe-global/safe-deployments/pull/93/files

Fix cronos mainnet address

---

safe_transaction_service/__init__.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/indexers/events_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py

Previously all RPC queries together were taken into account, so if there were a lot of queries even if the RPC was fast block process limit was not increased (or even decreased)

Auto adjust block limit for every RPC query

---

config/settings/base.py
safe_transaction_service/history/indexers/ethereum_indexer.py

- Make block process limit adjustment more optimistic (increase faster)
- By default query ERC20 transfers by batches of 1,000 instead of 5,000 (some networks cannot handle 5,000, and it can always be adjusted by envar)

Adjust defaults for indexer

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/urls.py
safe_transaction_service/history/views.py

Add a new endpoint `api/v1/about/erc20-indexing` that returns information about the ERC20 indexing status. Response will be:
```json
{
"current_block_number": "<str>",
"minimum_indexed_block_number": "<int>",
"synced": "<bool>",
}
```
- `current_block_number`: Current RPC block number.
- `minimum_indexed_block_number`: Block number for the less synced Safe (the one with the minimum indexed block number)
- `synced`: `True` if service is considered synced, `False` otherwise. Service will be considered `synced` if `minimum_indexed_block_number` is at least `ETH_REORG_BLOCKS` behind the `current_block`

Implement ERC20 indexing status endpoint

---

safe_transaction_service/history/management/commands/check_index_problems.py

- Erigon has a builtin EVM timeout of 5 seconds that can be exceeded when using Multicall

Allow forcing batch call for nonce retrieval

---

safe_transaction_service/__init__.py
safe_transaction_service/history/services/transaction_service.py

- Ethereum tx id is not present for modules and need to be taken using a join, so a index check is not possible
- A subquery using exists is way more optimal in this case

Fix all txs query

---

config/settings/base.py
safe_transaction_service/history/services/collectibles_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_collectibles_service.py
safe_transaction_service/history/tests/test_tasks.py

Closes #1027 
- Remove cache_memoize
- The task execution is delayed 30 seconds
- The retry_backoff is configured to 60 seconds and 4 retries as maximum , the retries is going to happen like following:
- first try at 30 seconds
- second try at 60 seconds
- third try at 120 secs
- fourth try at 240.
- fifth try at 480 secs

Collectibles cache invalidation

---

config/settings/base.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/events_indexer.py

All the Safe addresses reach the indexer, it splits the addresses in batches of `ETH_EVENTS_QUERY_CHUNK_SIZE`, queries the node and everything happens sequentially, so for `ETH_EVENTS_QUERY_CHUNK_SIZE=10` and `105 Safes` it will take 11 queries to the node.
As we are using round robin balancing with internal and external nodes multiple queries can be sent to multiple nodes, and that's why we will do it concurrently (configurable on the `ETH_EVENTS_GET_LOGS_CONCURRENCY` parameter, so we can adjust it depending on network conditions)

Perform ERC20 indexing concurrently

---

safe_transaction_service/history/tasks.py

Closes #1136 
- catch the exception
- implements a custom backoff retry 
- write a log message only when all retries were consumed
- the task finish always successfully

Reduce number of errors when can't get metadata

---

safe_transaction_service/history/management/commands/setup_service.py

What was wrong?
Mikomeda Algorand testnet was missing
How was it fixed?
* Added Milkomeda Algorand testnet addresses: https://github.com/safe-global/safe-deployments/pull/102 
* Added Milkomeda Algorand mainnet addresses: https://github.com/safe-global/safe-deployments/pull/132
Thanks folks 😄

Add Milkomeda algorand

---

safe_transaction_service/tokens/tasks.py
safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/views.py

Since tokens are indexed through an scheduled process, there's no need to make ad-hoc costly calls to the blockchain. This PR removes that functionality, so when a unknown token is requested, the service just responds 404 and does no further tasks.
Closes #
I removed both the task and the unit tests which covered it.

Remove tokens blockchain retrieval on 404

---

requirements.txt

https://github.com/safe-global/safe-eth-py/releases/tag/v4.7.1

Bump safe-eth-py from 4.7.0 to 4.7.1

---

safe_transaction_service/history/services/collectibles_service.py
safe_transaction_service/history/views.py

- Add missing kwargs for `_get_collectibles_with_metadata` call
- Add deprecated flag for `v1` collectibles endpoint on swagger
- Update `v1` collectibles endpoint docs on swagger
- 50 is an arbitrary number that the server should handle well and also should not impact normal users, only very big Safes

Limit v1 collectibles endpoint to 50

---

safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

- Closes #1148
- Start returning `confirmationsRequired` for transactions that are not executed (using the last available Safe status). Previously `null` was returned.

Add confirmationsRequired for not executed txs

---

safe_transaction_service/__init__.py
safe_transaction_service/history/indexers/tx_processor.py

- Previously, as we inherited the logic from the relay, it was possible that an ERC20 token was sent to a Safe address before the Safe was created, so by default we were indexing one day before was indexed.
- When a Safe was created the service could be marked out of sync even if it's not
- We were spending resources for a very rare case
- We can always index manually if needed
- Set v4.12.1 for a hotfix

Don't index events previous to a Safe creation

---

config/settings/base.py

Analytics tasks weren't added to any queue.

Add analytics task to contracts queue

---

safe_transaction_service/history/indexers/erc20_events_indexer.py

- Block range for ERC20 was not adjusted, so it was only decreasing on exceptions but never increasing again

Fix block range auto adjust for ERC20 indexer

---

.github/workflows/python.yml

- If not no event will be triggered on release and docker image will not be generated

Add release event to github actions

---

config/settings/base.py
safe_transaction_service/history/tasks.py

- An iterator was used to process InternalDecodedTx. Either all were processed, or none was be (atomic update)
- Refactor method so we process InternalTxDecoded in batches, so even if they take a lot to process service can slowly process them all
- This issue was detected on production with the indexer stuck for days processing a Safe with more than 11k of InternalTxDecoded

Process `InternalTxDecoded` in batches

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_safe_events_indexer.py

- Currently if tracing was enabled every RPC call from this service was performed to the tracing node, even if not required
- With this update, only tracing specific calls will be performed to the tracing node

Split tracing calls for TxProcessor and SafeService

---

requirements.txt

- Bump safe-eth-py version to 4.9.0 
https://github.com/safe-global/safe-eth-py/releases/tag/v4.9.0

Bump safe-eth-py to version 4.9.0

---

safe_transaction_service/history/indexers/safe_events_indexer.py

`ChangedMasterCopy` event was supposed to generate an argument `_masterCopy` instead of `masterCopy`. Due to a typo, it was not.

Fix processing `ChangedMasterCopy` event

---

safe_transaction_service/history/indexers/ethereum_indexer.py

Due to updating the variable before logging, the log message `block_process_limit %d is bigger than block_process_limit_max %d, reducing` had the same value for `block_process_limit` and for `block_process_limit_max`

Fix log message when reducing block range

---

safe_transaction_service/history/admin.py
safe_transaction_service/history/models.py

Search was not possible as it times out when no indexed fields are involved:
- Remove `arguments` field search
- Use exact search for `function_name` to use the db index

Fix InternalTxDecoded admin search

---

safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py

- Create a task to delete `not trusted` transactions older than one month
- Use `datetime.timedelta` instead of `timedelta` to prevent confusing `datetime` with `datetime.datetime`
- Closes #1212

Delete older not trusted transactions

---

.github/release.yml

- Dependabot will go into its own category
- PRs with `breaking_change` label will go in its own category
References:
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Configure automatic release notes

---

safe_transaction_service/history/services/reorg_service.py

The following line appear 2 times at the same instant: 
````
2023-02-03 08:58:07,200 [WARNING] [check_reorgs_task] Reorg found for block-number=16547174
2023-02-03 08:58:07,200 [WARNING] [check_reorgs_task] Reorg found for block-number=16547174
````
This PR remove one of them and leave the following in the task:
https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/history/tasks.py#L69

Remove duplicated warning log

---

requirements.txt
safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/tests/test_commands.py
safe_transaction_service/tokens/clients/coingecko_client.py
safe_transaction_service/tokens/migrations/0010_tokenlist.py
safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tests/clients/test_coingecko_client.py
safe_transaction_service/tokens/tests/migrations/test_migrations.py
safe_transaction_service/tokens/tests/test_price_service.py

- Rename required EthereumNetwork values
- Remove not existing networks

Update safe-eth-py to v5.0.0

---

safe_transaction_service/notifications/admin.py

Admin search for `FirebaseDeviceOwner` return an error because the field that the query is trying to search doesn't exist. 
The issue was that the search field was the `FirebaseDevice` instance instead the `uuid` field.

Fix admin search firebasedeviceowner

---

safe_transaction_service/history/views.py

Because it is not recommended to expose S3_BUCKET_NAME for security reasons.
For example: somebody could "steal" that S3 bucket in the future if it is available or send some specific attacts to it.

Remove sensitive info from About view

---

safe_transaction_service/__init__.py
safe_transaction_service/history/services/collectibles_service.py

- Fix performance issues detected on production
- We cannot deprecate the endpoint yet as mobile clients are still using it

Limit v1 collectibles endpoint to 10 collectibles

---

safe_transaction_service/history/tasks.py

This PR modify `reindex_last_hours_task` to avoid execute the `reindex_erc20_task` and `reindex_mastercopies_task` in parallel and do it sequentially. 
Closes #1329

reindex_last_hours_task executes sequentally each type of indexer

---

safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_erc20_events_indexer.py
safe_transaction_service/history/tests/test_proxy_factory_indexer.py
safe_transaction_service/history/tests/test_safe_events_indexer.py
safe_transaction_service/history/tests/test_tasks.py
safe_transaction_service/history/tests/utils.py

Close #1319 
This PR modify the return int of every indexer task to return a `Tuple[int, int]` where the second integer is the number of blocks processed by the task. 
-  def index_erc20_events_task(self) -> Optional[Tuple[int, int]]
-  def index_internal_txs_task(self) -> Optional[Tuple[int, int]]
-  def index_new_proxies_task(self) -> Optional[Tuple[int, int]]
-  def index_safe_events_task(self) -> Optional[Tuple[int, int]]
To achieve the PR purpose was necessary modify the return value of:
- `def start(self) ` to return a `Tuple[int, int]`  where the second int is the number of blocks processed
- ` def process_addresses(...)` to return `Tuple[Sequence[Any], int, int, bool]` where the second int is the `from_block_number`
- "Indexing of erc20/721 events task processed %d events" to …

Add the number of processed blocks to indexer tasks return

---

safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/tests/test_erc20_events_indexer.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_proxy_factory_indexer.py
safe_transaction_service/history/tests/test_safe_events_indexer.py

- Store next block to index in database instead of last indexed block
- Allow to process only 1 block (until now 2 was the minimum)
- Allow to index the current block number if `confirmations=0`

Refactor block range calculation for indexers

---

requirements.txt

Release note [v4.5.4](https://github.com/redis/redis-py/releases/tag/v4.5.4)

Bump redis version 4.5.4

---

safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py

- Previously when indexing in mixed `trace_filter`/`trace_block `mode last block for `trace_filter `was also indexed by `trace_block`
Also:
- Add more debug log messages on the indexers
- Update some function docstrings

Fix indexing same block with trace_filter and trace_block

---

safe_transaction_service/history/services/balance_service.py
safe_transaction_service/tokens/clients/binance_client.py
safe_transaction_service/tokens/clients/kraken_client.py
safe_transaction_service/tokens/clients/kucoin_client.py
safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tasks.py
safe_transaction_service/tokens/tests/clients/test_clients.py
safe_transaction_service/tokens/tests/test_price_service.py
safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/views.py

- `Token/ETH` value was retrieved in every network, but then the `Native token/USD` value was used to calculate the token `USD` value for every network.
- For example, for Gnosis Chain `Token/ETH` value was retrieved and then `DAI/USD` value was used to turn it into `USD`, instead of `ETH/USD`.
- Closes #1407

Fix USD prices for tokens

---

safe_transaction_service/history/tasks.py

Some critical errors on our indexer worker because countdown of 30 minutes.
`[CRITICAL] [???/???] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms.` 
The reason of that critical error is:
https://docs.celeryq.dev/en/stable/userguide/calling.html#eta-and-countdown 
> Warning
> 
> When using RabbitMQ as a message broker when specifying a countdown over 15 minutes, you may encounter the problem that the worker terminates with an [PreconditionFailed](https://docs.celeryq.dev/projects/amqp/en/latest/reference/amqp.exceptions.html#amqp.exceptions.PreconditionFailed) error will be raised:
> 
> amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - consumer ack timed out on channel …

Reduce delay countdown for reindex_erc20_events_task

---

safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py

Indexer tasks returned some times negative values to the number of blocks processed. 
The error was that from_block had the value of to_block and to_block the value of from_block. 
The error was solved setting this variables with the correct value.

Fix wrong order return values

---

safe_transaction_service/history/management/commands/setup_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py

The purpose of this PR is try to improve the accuracy of our current beat scheduler using crontab definitions.
See https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#crontab-schedules
Closes #1406 
Also because we can get more accuracy when the task is executed the `reindex_last_hours_task` was splitted in `reindex_last_hours_mastercopies_task` defeined every 2 hours at minute 0 and `reindex_last_hours_erc20_task` defined every 2 hours minute 30.

Add crontab schedule for periodic tasks

---

safe_transaction_service/history/tasks.py

Increment default time of reindex tasks to avoid missing blocks.
Define hours as float

Increment default time of reindex tasks

---

config/settings/base.py

- Use transient queues, as only reindexing tasks require durability: https://docs.celeryq.dev/en/latest/userguide/optimizing.html#using-transient-queues

Optimize Celery

---

requirements.txt
safe_transaction_service/contracts/tx_decoder.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/events_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py
safe_transaction_service/history/indexers/proxy_factory_indexer.py
safe_transaction_service/history/indexers/safe_events_indexer.py
safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/mocks/mocks_ethereum_tx.py
safe_transaction_service/history/tests/mocks/mocks_internal_tx_indexer.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/history/tests/test_safe_service.py
safe_transaction_service/history/tests/test_tx_processor.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/utils.py
safe_transaction_service/history/views.py
safe_transaction_service/safe_messages/tests/test_models.py
safe_transaction_service/tokens/clients/kleros_client.py
safe_transaction_service/tokens/migrations/0002_auto_20200903_1045.py
safe_transaction_service/tokens/models.py
safe_transaction_service/utils/serializers.py

- Bump safe-eth-py and modify the required tests for Web3 v6
- Take a look at https://web3py.readthedocs.io/en/stable/v6_migration.html#migrating-v5-to-v6

Bump safe-eth-py and refactor for Web3 v6

---

safe_transaction_service/history/services/transaction_service.py
safe_transaction_service/history/tests/test_transaction_service.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- `all-transactions` endpoint was returning only 1 module transactions when more than one `ModuleTransaction` had the same `txHash`
- More than one `ModuleTransaction` can be executed in a single transaction, so we refactor `getTransaction` method to be able to return multiple transactions for the same identifier
- Renames some variables and methods as `identifier` is more correct than `hash`
- Closes #1372

Return `ModuleTxs` with same `txHash` in all-transactions

---

safe_transaction_service/history/helpers.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Closes #1455 
Closes #1454 
Token transfer id should always finish with log_index value and internal_tx transfer_id should always finish with trace_address. 
Improved `is_valid_unique_transfer_id` to check if `transfer_id` contains valid `log_index` when is token transfer or valid `trace_address` when is an internal_tx.

Fix transfer_id validator

---

safe_transaction_service/history/services/webhooks.py
safe_transaction_service/notifications/tasks.py

- Fix issues with webhooks not working for networks not present in `EthereumNetwork`

Use chain_id instead of network for building webhooks

---

config/settings/base.py
safe_transaction_service/history/tests/test_transaction_service.py
safe_transaction_service/notifications/tasks.py
safe_transaction_service/notifications/tests/test_tasks.py
safe_transaction_service/notifications/tests/test_utils.py
safe_transaction_service/notifications/utils.py

- Use md5 hash of the payload instead of the payload
- Increase cache expiration time from 5 minutes to 2 hours
- Optimize redis check, so only one query is needed (by using SETNX)
- Refactor classes and tests

Fix duplicate notifications

---

safe_transaction_service/history/indexers/element_already_processed_checker.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/events_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/test_erc20_events_indexer.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_safe_events_indexer.py

- Txs/events were marked as processed in a optimistic way
- When txs/events were not processed due to an exception in the middle of the process, txs/events cannot be processed again as they were marked as processed
- Mark txs/events as processed only after they are inserted
- Improve logging for storing blocks, txs and receipts on database

Don't mark txs as processed before processing

---

safe_transaction_service/events/services/queue_service.py

If an issue during the first attempt connection happens, connection is not assigned properly that is ok, in this case we should use the connection passed as parameter on `on_connection_open_error` callback to retry the connection after 5 seconds. 
```
File "/app/safe_transaction_service/events/services/queue_service.py", line 143, in on_connection_open_error
self._connection.ioloop.call_later(5, self.connect)
AttributeError: 'NoneType' object has no attribute 'ioloop'
```

Fix connection is NoneType

---

safe_transaction_service/safe_messages/views.py

Swagger documentation  for `/v1/messages/{message_hash}/signatures/` and `/v1/safes/{address}/messages/` is indicating wrongly that the response includes a body.
Closes #1517

Fix swagger doc

---

.env.test

Local tests doesn't work because rabbitmq host was not defined.

Fix missing rabbitmq testing variable

---

requirements.txt

- Reverts safe-global/safe-transaction-service#1526
- Wait for https://github.com/axnsan12/drf-yasg/issues/856 to be released

Revert "Bump drf-yasg[validation] from 1.21.5 to 1.21.6"

---

config/settings/base.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py

- Increase default `ETH_REORG_BLOCKS` from `100` -> `150`
- Don't log all addresses when reindexing
- Remove not used anymore ALERT_OUT_OF_SYNC_EVENTS_THRESHOLD

Refactor reindexing

---

.env.test
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py

- It was disabled due to it taking a lot of resources
- When setting one Safe address to reindex instead of a lot reindexing is really fast

Reenable auto reindex of Safes when finding issues

---

config/settings/base.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/reorg_service.py
safe_transaction_service/history/tests/test_models.py

- I don't know why service was resetting to `250 blocks` before the reorg when finding a reorg. That's a lot and I guess is a typo. It was reduced to 10. Even leaving it to 0 should be alright.
- Erc20/721 indexing has no protection for reorgs. If a reorg happened it will keep indexing as it nothing happened, not reindexing the reorged blocks. Now if database block was reduced indexed status will not updated.
- Increase ETH_REORG_BLOCKS to 200 for every chain but mainnet. Looks like a safe assumption for all networks
- Add more logging to `ReorgService`

Fix reorg strategy

---

safe_transaction_service/history/helpers.py
safe_transaction_service/history/tests/test_views.py

For L1 chains trace_address can be empty string, then the `transfer_id` validator should include this case. 
Modifying the regular expression to include this case

Fix transfer_id validation

---

requirements.txt

Update safe-eth-py to 5.6.0 https://github.com/safe-global/safe-eth-py/releases/tag/v5.6.0

Bump safe-eth-py to 5.6.0

---

requirements.txt

Reverts safe-global/safe-transaction-service#1550
- Several connection issues were found with the last version of celery that didn't happened with 5.2.7.
- The connection issues are unrecoverable until worker restart https://github.com/safe-global/safe-transaction-service/issues/1566 
- Some issues related were opened on celery github https://github.com/celery/celery/issues?q=is%3Aissue+is%3Aopen+rabbit+
Closes #1566

Revert "Bump celery from 5.2.7 to 5.3.1"

---

safe_transaction_service/contracts/tx_decoder.py
safe_transaction_service/history/apps.py
safe_transaction_service/utils/redis.py
safe_transaction_service/utils/utils.py

- Tx decoder could take a few minutes to be loaded
- Before it was done by the first query that reached the tx service
- If there were multiple concurrent queries, tx service will be doing the computation multiple times, even if just one will be used for the cache
- Add logging to `get_redis` to find out if the same could be happening

Preload tx decoder when app starts

---

safe_transaction_service/history/services/transaction_service.py
safe_transaction_service/history/views.py
safe_transaction_service/utils/tasks.py

- Remove distinct from `ModuleTransaction`, as every `ModuleTransaction` is showed separated even if they share the same `ethereum txHash`
- Clean transaction_service, adding comments, renaming variables and refactoring typing
- Add logging to service and view
- Rename gevent variable for task locks (not very descriptive)

Refactor all-transactions endpoint

---

config/settings/base.py
docker/web/celery/scheduler/run.sh
docker/web/celery/worker/run.sh

Several issues are appearing on `rabbitMq` connections, ("connection reset by peer", "missing heartbeat"...) 
One possible reason could be due the high number of messages that celery are sending to keep the heartbeat, mingle and gossip. 
The following links explains a little bit more about it:
https://www.cloudamqp.com/docs/celery.html#commandline-arguments  
https://github.com/celery/celery/issues/4980
Also we change some default parameter that can be related: 
- pool connection to 0  https://github.com/celery/celery/issues/4355
- connection max retries to 0 (unlimited re-connection retries) 
- broker channel error to True, that enable retries when there is an issue with the channel connection. 
#1566

Add default celery configurations

---

README.md

- Some links pointing to the old Safe Dev Docs were updated
- A link pointing to the old Safe Service Client package was updated to point to the Safe{Core} SDK API Kit

Replace links in README

---

safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

`address`  field in `safeStatus` table is an index, adding this field to condition is reducing heavily the cost of the resultant query. 
The old query explain was as follows:
```
Gather Merge  (cost=1094612.73..1095395.38 rows=6708 width=46)
Workers Planned: 2
->  Sort  (cost=1093612.70..1093621.09 rows=3354 width=46)
Sort Key: history_safestatus.address, history_safestatus.nonce DESC, history_internaltx.block_number DESC, history_ethereumtx.transaction_index DESC, history_safestatus.internal_tx_id DESC
->  Hash Join  (cost=1019129.86..1093416.30 rows=3354 width=46)
Hash Cond: (history_safestatus.internal_tx_id = history_internaltx.id)
->  Parallel Seq Scan on history_safestatus  (cost=0.00..59969.29 rows=670829 width=38)
->  Hash  (cost=1014551.76..1014551.76 rows=263368 width=16)
-> …
```

Add address to filter condition

---

config/gunicorn.py
config/settings/base.py
gunicorn.conf.py
gunicorn_custom_workers.py
safe_transaction_service/utils/utils.py

- Store some gunicorn configuration in `/config`, so it can be used by Django
- Make sure psycopg is patched after the rest, and refactor it to the gunicorn worker
- Fix `running_on_gevent`, checking `socket` should be more accurate

Refactor gunicorn configuration

---

requirements.txt

Update safe-eth-version to v5.7.0 https://github.com/safe-global/safe-eth-py/releases/tag/v5.7.0
Most important change, gas increment for safe creation was removed.

Bump safe-eth-py to v5.7.0

---

safe_transaction_service/tokens/services/price_service.py
safe_transaction_service/tokens/tests/test_price_service.py

`get_token_eth_price_from_oracles` was returning ether value instead native token value when the price was returned from coingecko instead from oracles. 
Closes #1552

Fix get_token_eth_price_from_oracles

---

safe_transaction_service/history/models.py
safe_transaction_service/history/services/webhooks.py
safe_transaction_service/history/tests/test_signals.py
safe_transaction_service/safe_messages/signals.py
safe_transaction_service/safe_messages/tests/test_signals.py

The goal of this PR is send webhooks when a message is created, updated or confirmed. 
`process_webhook` was included in signals file of `safe_messages` app with some differences of the history signals method: 
- in this case is not necessary check if the notification is still relevant because the safe message have not `created` field.
- don't send notification to firebase. 
Two new types or webhook were included: 
- MESSAGE_CREATED
- MESSAGE_CONFIRMATION  
Also modify `build_webhook_payload`  to include payloads for message creation and confirmation following this specs https://github.com/safe-global/safe-transaction-service/issues/1240#issuecomment-1683585133 
Closes #1240

Add signal to trigger message webhook

---

safe_transaction_service/history/services/webhooks.py
safe_transaction_service/safe_messages/models.py

We shouldn't return message_hash as bytes format, only string format. 
`{'address': '0x0EDc6697427E9e9d62A1eE1A2951AfA7bE9e75B7', 'type': 'MESSAGE_CONFIRMATION', 'messageHash': b'W\xa5W\xd6$12\xbaV\x13\xb4\x15\xe6\x80\xea\x7f\tXN\xe5%L|\xe3\x92Z\x14\\\xc5\xd6\xb9\x1c', 'chainId': '5'}`
Converting the value from database to a hexadecimal string representation.

Messages webhok send bytes instead string

---

safe_transaction_service/history/indexers/ethereum_indexer.py

Some RPC node return 200 ok result and some random messages indicating an issue like for example "Block range too wide" that should indicate us that the block_process_limit configured have higher values than the RPC node accepts. 
To avoid stuck the indexer in this cases, a strategy could be reduce the indexer `block_process_limit` to one if this error happens. 
This PR add `ValueError` exception to  catch and reduce the block_process_limit to 1 as is done with other exceptions.

Catch ValueError for RPC Indexer errors

---

safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Closes #1614 
- Remove all sorting options except `execution_date`
- Check if correct sorting option was chosen 
- Add ordering test
- Add get all transactions view test

Remove all-transaction sorting options except execution_date

---

config/settings/base.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/reorg_service.py

- Until now, reorg handling was only checking "safe" blocks (with the required number of confirmations). That made the service really slow reacting to reorgs
- With this PR, all `not confirmed` blocks are checked, but only marking as confirmed the ones with the required number of confirmations
- `Previous block hash` check was removed, as it should be enough by checking the current returned block by the node
- Pagination is used to prevent having a lot of blocks of memory in the case of a service that went out of sync
- Pagination parameter was fixed to 250 by default as it's half of the value we use to index txs/blocks (using new configuration variable `ETH_REORG_BLOCKS_BATCH`)
- Closes #1554

Optimize reorg handling

---

safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/urls.py
safe_transaction_service/history/views.py

- `master-copies` endpoint will still be available
- Closes #1665

Deprecate master-copies endpoint and call it singletons

---

safe_transaction_service/safe_messages/admin.py

Closes #1678 
Contains search didn't work with hexstring. 
Fixed for every hexstring that message model contains.

Fix admin search for messages

---

safe_transaction_service/notifications/serializers.py
safe_transaction_service/notifications/tests/test_views.py
safe_transaction_service/notifications/utils.py

- When registering an owner for notifications, both signing the `hash` and the `hash` encoded using `EIP191` are valid
- Closes #1676

Support EIP191 for notifications registration

---

safe_transaction_service/events/tests/test_queue_service.py

When `RabbitMQ` keeps running, messages are not removed from the queue, which can cause issues during tests expecting different results.
The issue was fixed cleaning on setup the events queue.

Fix random issues on events queue tests

---

safe_transaction_service/history/views.py

- Gas estimation is only required for Safes < 1.3.0
- Safes < 1.3.0 are not supported in L2 chains
- Client gateway is calling this endpoint when getting the recommended nonce, even if it's not needed
- A lot of RPC calls are wasted
- Closes #614
Related:
- https://github.com/safe-global/safe-client-gateway/issues/681#issuecomment-1780677517

Disable gas estimation in L2 networks

---

safe_transaction_service/__init__.py

Hotfix to include [Disable gas estimation in L2 networks](https://github.com/safe-global/safe-transaction-service/pull/1722)

Set version to v4.27.1

---

safe_transaction_service/__init__.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Validator call was missing on #1722 
Added a test to try estimations with L2 networks
Set version to v4.27.2

Fix missing validator call

---

safe_transaction_service/contracts/admin.py
safe_transaction_service/history/admin.py
safe_transaction_service/notifications/admin.py
safe_transaction_service/safe_messages/admin.py
safe_transaction_service/tokens/admin.py
safe_transaction_service/utils/admin.py

- Implement new AdvancedAdminSearchMixin
- Don't convert every value to text for search, so DB indexes can be used
- Change admin search from `iexact (=)`  to `exact (==)`
- Closes #1710

Fix admin search slow

---

safe_transaction_service/__init__.py
safe_transaction_service/tokens/views.py

Price endpoint will be removed at `30/11/2024`. 
This PR marks price token endpoint as deprecated. 
#1758

Deprecate price endpoint

---

safe_transaction_service/history/tests/test_views.py
safe_transaction_service/tokens/serializers.py
safe_transaction_service/tokens/tests/test_views.py

Exposes the `trusted` field from the `Token` model entity. This field can be used for logic related to the reputation of a given token.

Add trusted field to token serialiser

---

safe_transaction_service/history/helpers.py
safe_transaction_service/history/models.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Allow deleting multisig transactions not executed

---

config/settings/base.py
config/settings/test.py
safe_transaction_service/events/services/queue_service.py

`Rabbitmq` is closing idle connections and `queue_service.is_connected` didn't detect the disconnection, then the new approach try to send and if can´t retry one more time.
- Disable `pika` logger

Fix queue_service connection issues

---

config/settings/base.py
safe_transaction_service/history/tests/test_proxy_factory_indexer.py

As indexer it's running quite well, we shouldn't require to reindex so many blocks

Reduce number of blocks to reindex again

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py

Accept zero address as `to` when posting transactions

---

safe_transaction_service/history/pagination.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Fix pagination issues for all-transactions

---

config/settings/base.py

This PR is enabling the configuration of print sql limit for debug purposes. 
The default limit set by `--print-sql ` in shell_plus is not enough for larger SQL queries.

Add Print SQL limit configuration

---

safe_transaction_service/history/models.py

- https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet.alias

Use alias instead of annotate to optimize queries

---

config/settings/base.py
docker/web/celery/worker/run.sh

- Liveness is not working if all the workers are busy
- Enable Celery events so we can monitor what's going on

Increase Celery concurrency to be able to handle PING

---

config/settings/base.py
config/settings/local.py
config/settings/production.py
docker/web/celery/worker/run.sh

- Stop storing results, as we are not using them.
- Remove `MAX_MEMORY_PER_CHILD` and `MAX_TASKS_PER_CHILD`, as they are not valid for `gevent` pool.

Update Celery configuration

---

requirements.txt
safe_transaction_service/history/tests/factories.py
safe_transaction_service/history/tests/test_index_service.py
safe_transaction_service/history/tests/test_migrations.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/history/tests/test_tx_processor.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/notifications/tests/test_tasks.py

- Depends on https://github.com/safe-global/safe-eth-py/pull/832
- Depends on https://github.com/safe-global/safe-eth-py/pull/834

Use fast_keccak when posible

---

config/settings/base.py
safe_transaction_service/history/services/transaction_service.py
safe_transaction_service/history/views.py

- Prevent issues with Safes receiving a lot of transfers every second
- Closes #1930

Limit Transfers

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/history/tests/test_tx_processor.py

Closes #1850
The delegate should only be removed if it is specifically from the safe and the owner. If it is a general delegate for a user, it should not be deleted.

Delete delegates from safe and owner when owner is removed

---

safe_transaction_service/history/views.py

Add logs to debug the cache key in the all-transactions endpoint.

Add cache key to debug logs

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/tests/test_views.py
safe_transaction_service/account_abstraction/views.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_views.py

- Refactor `SafeOperationResponseSerializer`, previously it was using a `UserOperation` to render the fields, now it uses a `SafeOperation`
- Refactor tests

4337: Add SafeOperation to creation endpoint

---

safe_transaction_service/account_abstraction/serializers.py

- HexBytes must be used so `0x` prefixed strings are supported

Paymaster cannot be processed using `bytes`

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/tests/test_views.py

- Fix `valid_after` and `valid_until` parsing
-  Fix `valid_until` check

4337: Fix `valid_after` and `valid_until` parsing

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/services/aa_processor_service.py

As a first step we disabled indexing of failed user operations, but they should be indexed too. Also a user operation can deploy a Safe and then fail

4337: Index failed user operations

---

safe_transaction_service/account_abstraction/services/aa_processor_service.py
safe_transaction_service/account_abstraction/utils.py
safe_transaction_service/history/management/commands/check_chainid_matches.py
safe_transaction_service/history/tests/test_commands.py

Check if ETHEREUM_4337_BUNDLER_URL uses the correct chainId

---

requirements.txt

Updates safe-eth-py to v6.0.0b7

Bump safe-eth-py to v6.0.0b27

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/mocks/deployments_mock.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/urls.py
safe_transaction_service/history/views.py

Add a new endpoint to return the Safe deployments from https://github.com/safe-global/safe-eth-py/blob/main/gnosis/safe/safe_deployments.py 
The new endpoint can be queried by version or/and contract name providing it by query parameter.
This PR also includes the swagger documentation for this new endpoint. 
Closes #1996

Add safe deployments endpoint

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/services/aa_processor_service.py
safe_transaction_service/account_abstraction/tests/test_views.py
safe_transaction_service/account_abstraction/urls.py
safe_transaction_service/account_abstraction/views.py

- Sometimes SafeOperation is reverted and the only existing information is the UserOperation
- Related to #2035

4337: Add endpoint to return UserOperations

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/tests/test_views.py
safe_transaction_service/account_abstraction/views.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_views.py

- `user-operations` endpoints should return `safeOperation` if there's one for the `userOperation`
- Related to #2035

4337: Add `safeOperation` inside of `userOperation` serializer

---

safe_transaction_service/account_abstraction/views.py

- Endpoint should not allow POST.
- SafeOperations must be created from the `safe-operations/` endpoint.

4337: Remove UserOperation POST method

---

config/settings/base.py
safe_transaction_service/utils/swagger.py

- Closes #2036
Currently tags are generated using the first path in the url, like `v1` or `v2`.
We are now defining some logic to generate `tags`:
- If they are explicitly defined in the view, we keep that (`self.overrides`).
- If the `operation_id` contains any of the words defined, we override the tag.
- Otherwise, just iterate the `operation_keys` and return

Add logic to define Swagger tags

---

.github/workflows/python.yml

From docker [V26](https://github.com/docker/cli/blob/v26.1.3/docs/deprecated.md) is necessary to explicitly create user defined network instead to directly use ` --network-alias`

Explicitly create user defined network

---

safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py
safe_transaction_service/history/indexers/events_indexer.py
safe_transaction_service/history/indexers/internal_tx_indexer.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_commands.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_tasks.py

Make indexers use `sets` instead of db instances
- Previously, `MonitoredAddress` instances were used.
- Currently, only `address` is retrieved from database, and transformed into a set
- This approach is:
- More optimal both on CPU/RAM, as it does not have to use a `list` and then convert to a `set`
- Easier to cache (in a following PR)
- Easiert to extend and implement new indexers
- Tests and indexers were refactored
- Typing was checked and fixed

Optimize load of addresses in indexer

---

safe_transaction_service/history/helpers.py
safe_transaction_service/history/tests/test_helpers.py
safe_transaction_service/history/views_v2.py

Closes #2084
The Delegate EIP712 payload was using `bytes32` as the type for the delegate address (which is an Ethereum Address).
While this works, it represents the wrong input type and size constraints that we should accept for that field (an address is 20 bytes so any input bigger than that should not be valid).
Signatures made before this change will not be considered valid as the resulting has would be different. The new payload would need to be signed again by the required signers again in those scenarios.

Use address type for EIP712 payload

---

safe_transaction_service/__init__.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/test_commands.py

- A `set` should be passed, not a list, so check can be instant

Fix ERC20 reindex

---

safe_transaction_service/history/views.py
safe_transaction_service/history/views_v2.py

Related with https://github.com/safe-global/safe-transaction-service/issues/2071
Detected in QA validation. Missed in https://github.com/safe-global/safe-transaction-service/pull/2114

Add code marks to swagger descriptions

---

run_tests.sh

There might be situations where `docker compose up` tries to add an existing container to a network that no longer exists (Docker daemon returns an error in those cases).
For a test script, we do want to have a new environment (network) created which the new containers can interact with.
See https://docs.docker.com/reference/cli/docker/compose/up/

Force recreate containers in test script

---

safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_index_service.py

- When processing transactions, if there is a reindex a old transaction can appear between the already processed ones
- Previously, the solution for that was removing status for the Safe and then process all the transactions again
- This was not optimal at all for Safes with a high number of transactions, so this PR will only reprocess transactions from the problematic timestamp

Optimize out of order tx processing

---

config/settings/base.py
requirements.txt
safe_transaction_service/history/services/collectibles_service.py

- Adds the possibility to add an ENS Subgraph configuration.
- The Subgraph requires an API key which can be obtained via The Graph interface (https://thegraph.com/docs/en/querying/querying-the-graph/)
- Adds three environment variables that should be used if The Subgraph support needs to be enabled:
* `ENS_SUBGRAPH_URL` – the base url to query the subgraph from
* `ENS_SUBGRAPH_API_KEY` – the API key that was obtained from The Graph
* `ENS_SUBGRAPH_ID` – the subgraph id. An example of an ENS Subgraph can be found in https://thegraph.com/explorer/subgraphs/5XqPmWe6gjyrJtFn9cLy237i4cWw2j9HcUJEXsP5qGtH?view=Query&chain=arbitrum-one. To query this graph, you should use `5XqPmWe6gjyrJtFn9cLy237i4cWw2j9HcUJEXsP5qGtH` as the subgraph id.
- The ENS Subgraph configuration is only required if …

Add ENS Subgraph configuration

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/tests/test_views.py

SafeOperation calculation requires timestamp in milliseconds

4337: Use timestamps with milliseconds

---

safe_transaction_service/account_abstraction/serializers.py
safe_transaction_service/account_abstraction/tests/test_views.py

- Reverts safe-global/safe-transaction-service#2134
- Timestamps are in seconds

Revert "4337: Use timestamps with milliseconds"

---

safe_transaction_service/history/services/balance_service.py

When a new token was transferred to a `Safe`, `Token` filtering was made when it was not yet stored in the database. This is why `Token` transaction amounts that did not exist in the database were not returned in the response.
Additionally, the global counter is fixed. If a filter is applied to the request, it must be taken into account when calculating the total number of items to which it applies.

Fix get balance new tokens filter

---

safe_transaction_service/account_abstraction/views.py

- Sorting only by `nonce` can be unstable
- Sort `SafeOperations` by `created` too
- Sort `UserOperations` by `the block timestamp` too

4337: Make sorting stable for Safe/User Operations

---

safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/test_index_service.py

- If SafeStatus is removed, `SafeLastStatus` cannot be generated and fixing cannot be performed

Don't generate SafeLastStatus when fixing out of order txs

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py

- It shouldn't be an issue, but I think it's cleaner
- Improve logging
- Return `boolean` when cleaning `TxProcessor` cache

Clean cache after deleting txs

---

requirements.txt

- Avoiding a type error in the CI

Bump web3 from 6.20.0 to 6.20.2

---

safe_transaction_service/history/services/transaction_service.py
safe_transaction_service/history/signals.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

Closes #2188 
- The cache is added again to the all-transactions endpoint, which had been removed in this [PR](https://github.com/safe-global/safe-transaction-service/pull/2166)

Add cache to all-transactions endpoint

---

safe_transaction_service/history/tasks.py

Add one line to `process_decoded_internal_txs_task` to identify when the task is starting.

Add log info to process_decoded_internal_txs_task

---

config/settings/local.py
docker/nginx/nginx.conf

Try endpoints from swagger always failed because the port was not included.
-  X_FORWARDED_HOST were configured in  nginx but were not enabled in Django.
- $server_name is not configured, using the host instead.

Fix swagger locally is not working

---

safe_transaction_service/history/models.py
safe_transaction_service/history/services/balance_service.py
safe_transaction_service/history/tests/test_models.py

Query for used tokens
---------------------
Before:
```
EXPLAIN ANALYZE SELECT DISTINCT "history_erc20transfer"."address"
FROM "history_erc20transfer"
WHERE ("history_erc20transfer"."to" = '\x930dedddb92fef1b4ab2665d250877339f064eac'::bytea OR "history_erc20transfer"."_from" = '\x930dedddb92fef1b4ab2665d250877339f064eac'::bytea);
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------
HashAggregate  (cost=2871805.29..2871815.76 rows=1047 width=21) (actual time=96564.298..96565.725 rows=1344 loops=1)
Group Key: address
Batches: 1  Memory Usage: 193kB
->  Gather  (cost=1000.00..2865068.91 rows=2694550 width=21) (actual time=1.969..96005.333 rows=2665149 loops=1)
Workers Planned: 2 …
```

Optimize queries for ERC20 balances

---

safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_tasks.py

- If a Safe was banned, InternalTxDecoded were never marked as processed
- Because of that, InternalTxDecoded index for `processed=True` grew with no control
- At some point, the query to get the pending `InternalTxDecoded` to process could take a few minutes, delaying indexing of Safe transactions
- Related to #2214

Mark banned Safes InternalTxDecoded as processed

---

safe_transaction_service/history/models.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_index_service.py
safe_transaction_service/history/tests/test_tasks.py

- Task was refactored into a function in `IndexService`
- Automatic reindexing of Safes was disabled. Reindexing issues should be fixed by the scheduled task `reindex_mastercopies_last_hours_task`. Also some Safes were corrupted due to users trying to trick the indexer or Safes converted from L1 -> L2, and reindexing was triggered forever
- Closes #2214

Refactor processing of Internal Txs

---

safe_transaction_service/notifications/clients/firebase_client.py
safe_transaction_service/notifications/tasks.py
safe_transaction_service/notifications/tests/test_firebase_client.py

We are having issues because `send_multicast` was deprecated, updating to the new function with the same purpose.

Update deprecated firebase function

---

docker/web/celery/worker/run.sh
safe_transaction_service/contracts/management/commands/setup_safe_contracts.py
safe_transaction_service/contracts/tests/test_commands.py

- Add MultiSend contract to enable for trusted delegate call

Refactor command name

---

requirements.txt

- asgiref was broken a few versions ago and was pinned, it should not be required anymore

Unpin asgiref

---

requirements.txt
safe_transaction_service/contracts/management/commands/setup_safe_contracts.py
safe_transaction_service/contracts/tests/test_commands.py
safe_transaction_service/contracts/tx_decoder.py
safe_transaction_service/history/tests/mocks/deployments_mock.py

Closes #2243 
- Updated the tests with the new contract addresses in the `safe_deployments` file of `safe-eth-py`.

Add SafeToL2Migration contract abi

---

safe_transaction_service/analytics/tasks.py
safe_transaction_service/contracts/tasks.py
safe_transaction_service/history/tasks.py
safe_transaction_service/tokens/tasks.py
safe_transaction_service/utils/celery.py

This PR adds a custom timeout using the `gevent` timeout (the same that is using Celery) adding some improvements to Celery implementation:
- Log the task timeout errors following our log format
- Can raise an exception if necessary
- Task timeouts can be retried
- Remove unused soft timeout (`Celery` with `gevent` is not using it)
```
@app.shared_task(bind=True,
soft_time_limit=2,
time_limit=5,
autoretry_for=(TimeLimitExceeded,),
default_retry_delay=15,
retry_kwargs={"max_retries": 3},)
def task_timeout_error(self):
url = "https://httpbin.org/delay/10"
logger.info("Start task_timeout_error")
response = requests.get(url, timeout=10)
```
Output:
```
indexer-worker-1  | 2024-10-10 11:52:08,306 [INFO] [36eb5567/task_timeout_error] Start task_timeout_error
indexer-worker-1  | 2024-10-10 …
```

Add custom timeout decorator

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/services/index_service.py

- TxProcessor was shared between tasks, so cache was deleted for all of them
- Now only the involved Safe is deleted from the processor
- If there's an error processing a transaction, previously cache could become broken. Now a `finally` is used to make sure it's always cleaned

Fix caching issues on tx-processor

---

safe_transaction_service/history/models.py
safe_transaction_service/history/tests/test_models.py

Fix `null` confirmationsRequired on txs endpoint
Now, for an historical transaction, we follow the same rules:
- If there's an entry on `SafeStatus` with matching `nonce` and `safe_tx_hash`, it's returned.
- If not, if there's an entry on `SafeLastStatus` with matching `nonce` and `safe_tx_hash`, it's returned.
- Otherwise, the number of confirmations for that transaction is returned.
Closes #2170

Fix `null` confirmationsRequired

---

safe_transaction_service/contracts/management/commands/setup_safe_contracts.py
safe_transaction_service/contracts/tests/test_commands.py

Closes #2266
- Rename `--force-update-contract-names` option

Enable SignMessageLib as trusted for delegates by default

---

safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/mocks/blocks.py
safe_transaction_service/history/tests/test_views.py

- It looks like that due RPC balancing, sometimes there are blocks missing
- This way we minimize the chance of having issues, as we recover first the last block and the other blocks can only be equal or smaller than that one

Fix indexing endpoint

---

safe_transaction_service/tokens/tasks.py

- Address was not checked and could be `None`.
- If `chainId` is not specified, we assume it's matching the current one.
- Exclude tokens without `address`

Fix `update_token_info_from_token_list_task`

---

docker/web/celery/worker/run.sh
safe_transaction_service/history/tasks.py
safe_transaction_service/utils/tasks.py

- By default now is `2` (it was `4`)
- Clean some code in tasks

Allow configuration for Celery Prefetch Multiplier

---

config/settings/base.py
safe_transaction_service/history/tasks.py

Adding the configurable queue names to be able to move some tasks to other workers. 
For now just process_safes have a different variable.

Move process_decoded_internal_txs_for_safe_task to processing queue

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/views.py

- Closes #2284
- Delegate users can only delete transactions proposed by themselves.
- Delegate users must still be valid at the time of deletion.

Add support for delegates to delete transactions proposed by themselves

---

config/settings/base.py
safe_transaction_service/history/services/index_service.py

- For some network, out of order check of transactions is really slow
- Taking as an example the last week, we only observed one out of order issue in the logs
- With this PR we can configure it via environment variables to speed up transaction processing

Make out of order check optional

---

safe_transaction_service/history/services/notification_service.py
safe_transaction_service/history/tests/test_signals.py

- Related with #2299 
All events processed by the events service expect the name of the attribute containing the address of the safe to be in the address attribute. [Example](https://github.com/safe-global/safe-events-service/blob/d58e3427fbbd7cc795ebe335ba5ba866a5791bf3/src/routes/events/events.service.ts#L33)

Fix delegates events payload attribute name

---

config/settings/base.py
safe_transaction_service/history/indexers/erc20_events_indexer.py
safe_transaction_service/history/indexers/ethereum_indexer.py

- Closes #2301
Use database iterators to load ERC20 addresses, so only chunks are loaded in RAM, instead of the whole queryset. Using production database I analyzed good values for `chunk_size` value:
```
Chunk size optimization
-----------------------
Testing with 3M Safes
2k - 90 seconds
100k - 73 seconds
500k - 60 seconds
1M - 60 seconds
3M - 60 seconds
Testing with 15M Safes
50k - 854 seconds
500k - 460 seconds
750k - 415 seconds
1M - 430 seconds
2M - 398 seconds
3M - 407 seconds
500k sounds like a good compromise memory/speed wise
```

Optimize load of ERC20 addresses

---

safe_transaction_service/history/services/safe_service.py
safe_transaction_service/history/tests/test_safe_service.py
safe_transaction_service/history/tests/test_views.py

- Closes #2309
In some cases more than one result was being returned for the query. The CREATE filter is added to return only the creation Tx.
A test case is added to check this case.

Fix get_safe_creation_info query

---

safe_transaction_service/tokens/serializers.py
safe_transaction_service/tokens/tests/factories.py
safe_transaction_service/tokens/tests/test_views.py
safe_transaction_service/tokens/urls.py
safe_transaction_service/tokens/views.py

Add endpoint `/tokens/lists`

---

safe_transaction_service/history/indexers/tx_processor.py

Sometimes when reindexing a safe, if a missing Tx appears, it is being inserted with the current date instead of the correct date. 
This causes an order problem in the `all-transactions` endpoint.

Fix SafeRelevantTransaction default timestamp

---

safe_transaction_service/history/services/collectibles_service.py

The URL https://api.thegraph.com/subgraphs/name/ensdomains/ens is no longer supported and it is necessary to use the ENS Mainnet subgraph (https://thegraph.com/explorer/subgraphs/5XqPmWe6gjyrJtFn9cLy237i4cWw2j9HcUJEXsP5qGtH) and the subgraph config to make the same queries to the TheGraph api.
- Related with https://github.com/safe-global/safe-eth-py/issues/1481

Remove ens client mainnet base url

---

safe_transaction_service/history/views.py

Small typo in the multisig_transaction DELETE path.
Fixed the typo manually

Fix typo in views.py

---

safe_transaction_service/history/services/notification_service.py
safe_transaction_service/history/tests/test_signals.py

Add "to" field to PENDING and EXECUTED multisig tx events

---

.github/workflows/python.yml
config/settings/base.py
docker-compose.yml
gunicorn_custom_workers.py
requirements.txt
safe_transaction_service/history/admin.py
safe_transaction_service/history/management/commands/export_multisig_tx_data.py
safe_transaction_service/history/migrations/0016_multisigconfirmation_signature_type.py
safe_transaction_service/history/serializers.py

- https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html
- https://docs.djangoproject.com/en/dev/releases/4.2/#psycopg-3-support

Update psycopg2 to psycopg3

---

safe_transaction_service/history/services/notification_service.py
safe_transaction_service/history/tests/test_signals.py
safe_transaction_service/notifications/tasks.py

- Required for Multisend support on the **data decoder**
- `data` will not be sent to Firebase, as it can exceed the maximum message size

Send data for the MULTISIG_TRANSACTION payloads

---

safe_transaction_service/history/serializers.py
safe_transaction_service/history/services/transaction_service.py
safe_transaction_service/history/tests/test_views.py
safe_transaction_service/history/tests/test_views_v2.py
safe_transaction_service/history/urls_v2.py
safe_transaction_service/history/views.py
safe_transaction_service/history/views_v2.py

Add V2 endpoint for the new return types on multisigtransaction. 
- GET `/api/v1/multisig-transactions/{safe_tx_hash}/`
- DELETE `/api/v1/multisig-transactions/{safe_tx_hash}/`
- GET `/api/v1/safes/{address}/multisig-transactions/`
- POST `/api/v1/safes/{address}/multisig-transactions/`
- GET `/api/v1/safes/{address}/all-transactions/`
- GET `/api/v2/multisig-transactions/{safe_tx_hash}/`
- DELETE `/api/v2/multisig-transactions/{safe_tx_hash}/`
- GET `/api/v2/safes/{address}/multisig-transactions/`
- POST `/api/v2/safes/{address}/multisig-transactions/`
- GET `/api/v2/safes/{address}/all-transactions/`
The endpoints behind version two modify the types int for string for the following properties. 
```
nonce : <String>
base_gas : <String>
safe_tx_gas : <String>
```

Add V2 for multisigtransaction and all-transactions endpoints

---

config/settings/local.py

This pull request corrects a typo in the `local.py` file. The word "Mimicing" has been corrected to "Mimicking."
- Fixed the typo **"Mimicing"** to **"Mimicking"** in the `local.py` file.

typo fix local.py

---

config/settings/base.py
safe_transaction_service/history/services/collectibles_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_collectibles_service.py
safe_transaction_service/history/tests/test_tasks.py

Add COLLECTIBLES_ENABLE_DOWNLOAD_METADATA to enable or disable the metadata download with False (disabled) by default.

Add flag to disable download collectibles

---

safe_transaction_service/history/indexers/ethereum_indexer.py

Added Web3RPCError exception to avoid errors like `web3.exceptions.Web3RPCError: {'code': -32602, 'message': 'Query returned more than 10000 results. Try with this block range [x, y].'}`

Fix ethereum indexer RPC calls exceptions

---

safe_transaction_service/history/indexers/safe_events_indexer.py

- Event can be indexed if there are more Safe related events on the ethereum tx, but it must not be processed

Don't process SafeReceived event for zksync networks

---

requirements.txt
safe_transaction_service/history/tests/test_commands.py
safe_transaction_service/history/tests/test_safe_service.py

- Previously fallback handler v1.4.1 was used for v1.3.0 Safes

Use correct fallback handler versions

---

safe_transaction_service/history/helpers.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_helpers.py
safe_transaction_service/history/tests/test_views_v2.py

- Related with #2472 
Fixed the validation of EIP-1271 signatures so a nested safe can add a delegate user for its Safe owner using a 1271 signature.
Added a test case where the scenario described in the open issue is validated.

Fix 1271 signatures for delegates

---

safe_transaction_service/safe_messages/serializers.py
safe_transaction_service/safe_messages/tests/factories.py
safe_transaction_service/safe_messages/tests/test_models.py
safe_transaction_service/safe_messages/tests/test_views.py

- Revert to the old behaviour, so we don't break the frontend
- For 1271 `isValid` accepts hashes instead of full data

Use hashes instead of full message for 1271

---

config/settings/base.py
safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/models.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_index_service.py
safe_transaction_service/history/tests/test_internal_tx_indexer.py
safe_transaction_service/history/tests/test_safe_events_indexer.py
safe_transaction_service/history/tests/test_tasks.py

Process every Safe together:
- Less database sessions/transactions
- Less database queries to get internal txs for every Safe

Optimize tx processing

---

safe_transaction_service/history/indexers/tx_processor.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/tests/test_tx_processor.py

- Previously, an error could stuck the processor
- Indexing issues can be detected and fixed even if errors are ignored
- Malicious transactions and custom crafted Safes could stuck the indexer

Ignore errors on tx processing

---

safe_transaction_service/history/models.py
safe_transaction_service/history/services/index_service.py
safe_transaction_service/history/tests/test_models.py

- Previously, there were inserted individually
- This should be quite faster for indexing/reindexing

Insert EthereumTxs and EthereumBlocks in batch

---

safe_transaction_service/history/services/reorg_service.py
safe_transaction_service/history/tests/test_reorg_service.py

- Test was flaky. Probably due to not sort multisig txs. Added `.order_by("created")`
- Add more test cases and improve the tests
- Also fix a bug that reset `ERC20 Indexing` to the reorg block even if ERC20 indexing was behind

Fix `test_recover_from_reorg` test

---

safe_transaction_service/contracts/views.py
safe_transaction_service/history/serializers.py
safe_transaction_service/history/views.py

Mark as deprecated and add documentation guidance for migration for every decoding endpoint or field.
closes #2601

Add doc for deprecated decoding endpoints

---

safe_transaction_service/history/models.py
safe_transaction_service/utils/tasks.py

- `DISTINCT` is way faster compared to `DISTINCT ON`
Old query:
```
EXPLAIN ANALYZE SELECT DISTINCT ON ( history_internaltx._from ) history_internaltx._from FROM history_internaltxdecoded INNER JOIN history_internaltx ON ( history_internaltxdecoded.internal_tx_id = history_internaltx.id ) WHERE NOT history_internaltxdecoded.processed;
----------
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------
Unique  (cost=27762085.14..34014641.74 rows=82268 width=21) (actual time=1084398.509..1121931.248 rows=6834483 loops=1)
->  Gather Merge  (cost=27762085.14..33886761.53 rows=51152084 width=21) (actual …
```

Optimize get pending Safes query

---

config/settings/base.py
requirements.txt
safe_transaction_service/contracts/tasks.py
safe_transaction_service/history/tasks.py
safe_transaction_service/history/tests/test_models.py
safe_transaction_service/tokens/tasks.py
safe_transaction_service/utils/tasks.py
safe_transaction_service/utils/tests/test_tasks.py
safe_transaction_service/utils/utils.py

- Migrate `django-db-geventpool` to native `psycopg3` pool
- Remove `django-db-geventpool` required boilerplate to close connections

Update to Django 5.2

---

config/settings/base.py

Disables by default the check if `to` is  a Trusted Delegate contract for delegate calls.

Disable by default trusted delegate calls
